### ISSUE TITLE
2.2.4 JS의 덕 타이핑, 타입스크립트의 구조적 타이핑의 공통점 및 차이점은 어떤 것들이 있을까요?

### ISSUE THREAD

**Issue by Clt689** [Gwangju-Web-Study/WoowahanTS_Study#10]
📝 46p ~ 48p

❓ 타입스크립트의 구조적 타이핑은 자바스크립트의 덕 타이핑을 기반으로 한다고 교재에 명시되어 있습니다. 

그렇다면 자바스크립트의 덕 타이핑과 타입스크립트의 구조적 타이핑의 **공통점 및 차이점**은 어떤 것들이 있나요?

**Comment by db-jay** [comment]
### 공통점
1. 객체의 구조에 기반한 타입 결정.
    1. 두 방식 모두 객체가 어떤 속성과 메서드를 가지고 있는지에 따라 타입을 결정함.
    2. 객체의 실제 구조가 중요하며, 명시적인 타입 선언이나 상속 관계는 부차적임.
2. 타입 선언을 생략하면 암시적 타입 변환 발생.
    1. 명시적으로 인터페이스를 구현하거나 상속받지 않아도 필요한 구조만 갖추면 특정 타입으로 취급됨.
3. 코드 재사용성
    1. 기존 코드를 변경하지 않고도 새로운 타입의 객체를 기존 함수나 메서드와 함께 사용 가능함.

### 차이점

1. 덕타이핑(JS)
    1. 런타임에 타입을 검사. 
    2. 주로 동적 타이핑에서 사용.
    3. 런타임 에러가 발생할 가능성 높음.
    4. 타입을 명시적으로 선언하지 않음.
    5. 유연성 높지만 시스템을 예측하기 어려움.
2. 구조적 타이핑(TS)
    1. 컴파일 시점에 타입 체커가 타입을 검사.
    2. 주로 정적 타이핑에서 사용.
    3. 컴파일 시 타입 오류를 체크해서 더 높은 안정성 제공.
    4. 타입을 명시적으로 선언할 수 있으며, 선언을 바탕으로 타입 검사.
    5. 덕타이핑의 유연성을 유지하면서 타입 시스템의 안정성 제공.

### 코드 비교

```tsx
// 서로 다른 구조의 객체들
const user = { name: "Jay", lv: 1 };
const repository = { title: "WoowahanTS_Study", user: "Jay" };

// ✅ 덕 타이핑 예제
function logName(obj) {
  console.log(obj.name);
}

// 모두 'name' 속성을 가지고 있어 함수 호출 가능
logName(user);  // 출력: Jay
logName(repository);    // 출력: undefined (런타임 에러 발생하지 않음)

// 런타임에 에러 발생
try {
  logName({ price: 100 });  // TypeError: Cannot read property 'name' of undefined
} catch (error) {
  console.error("런타임 에러 발생:", error.message);
}

// ✅ 구조적 타이핑 예제
interface Named {
  name: string;
}

function logName(obj: Named) {
  console.log(obj.name);
}

// 컴파일 시점에 타입 검사 & 에러 발생
logName(user);  // 정상
// logName(repository); // 컴파일 에러: 'Named' 타입에 필요한 'name' 속성이 '{ title: string; user: string; }' 타입에 없습니다.

```

**Comment by hyeonseong2023** [comment]
| 항목          | 덕 타이핑 (JavaScript)                              | 구조적 타이핑 (TypeScript)                         |
|---------------|-----------------------------------------------------|------------------------------------------------------------|
| 정의           | 객체가 특정 메서드나 속성을 가지고 있으면 해당 타입으로 취급 | 타입이 특정 구조를 가지면 그 타입으로 취급                      |
| 타입 체크 시점     | 동적 타이핑에서 사용되며, 런타임에 타입 체크를 수행 | 정적 타이핑에서 사용되며, 컴파일 타임에 타입 체크를 수행   |
| 유연성         | 높은 유연성 제공 | 정확한 타입 일치 요구       |
| 타입 명시      | 명시적인 타입 선언이 없음                           | 명시적인 타입 선언이 필요함                                 |

**Comment by gwangminjun** [comment]
## 덕타이핑

만약 오리처럼 걷고 오리처럼 꽥 소리를 낸다면, 그것은 분명히 오리이다.

변수에 어떠한 타입의 값도 할당할 수 있는것

ts : 여러 타입을 조합한 새로운 타입을 가지는것

### 타입스크립트에서 덕 타이핑 사용
#### 유니온 타입
```ts
type Team = "Red" | "Blue"
```
#### 제네릭 타입
어떠한 타입이든 정의될 수 있지만 호출되는 시점에 타입이 결정
```ts
function ide<T> (arg:T):T{
    return arg;
}
```


## 구조적 타이핑

타입이 특정 구조를 가지면 그 타입으로 취급

### 타입스크립트에서 구조적 타이핑 사용
#### DB에 따른 유닛 테스트 작성
```ts
// 추상적인 interface를 만들고, 
// 상속이 아닌 구조적 타이핑으로 PostgresDB, FirebaseDB 등 
// 다양한 DB에 대한 구조 검증
interface Author {
  first: string;
  last: string;
}

interface DB {
  runQuery: (sql: string) => any[]; //결과를 이차원 배열로 반환
}

function getauthors(database: DB): Author[] {
  const authorRows = database.runQuery(`SELECT FIRST, LAST FROM AUTHORS`); //이차원 배열 획득
  return authorRows.map(row => ({ first: row[0], last: row[1] }); // Author 구조에 맞게 변환하여 반환
}

//유닛 테스트
test('getAuthors', () => {
  const authors = getAuthors({
    runQuery(sql: string) {
      return [['Toni', 'Morrison'], ['Maya', 'Angelou']];
      // 가짜 DB 객체 사용
    }
  });
  //바른 형태의 Author 배열을 반환하는지를 검증
  expect(authors).toEqual([
    {first: 'Toni', last: 'Morrison'},
    {first: 'Maya', last: 'Angelou'}
  ]);
});
```

### 덕 타이핑 과 구조적 타이핑 공통점
1. 구조기반 타입 판단
    - 객체의 실제 구조 기반 판단
2. 유연성
    - 명시적인 상속관계 없이도 동일한 프로퍼티와 메서드를 가진 객체는 그 타입으로 인정


### 덕 타이핑 과 구조적 타이핑 차이점
1. 타입 검증 시점
    - 덕 타이핑 : 런타입 시점에 타입을 확인
    - 구조적 타이핑 : 컴파일 시점에 타입 확인
2. 정적 분석
    - 덕 타이핑 : 런타임 시점에 타입을 확인 -> 런타입 오류 증가
    - 구조적 타이핑 : 코드 작성 시점에 타입 검증을 수행하기 때문에 런타임 오류가 적다
### reference
- https://kfdd6630.tistory.com/entry/js-%EB%8D%95-%ED%83%80%EC%9D%B4%ED%95%91duck-typing#google_vignette
- https://openmaker.tistory.com/142
- https://en.wikipedia.org/wiki/Duck_typing
- https://en.wikipedia.org/wiki/Structural_type_system

**Comment by BaekWeb** [comment]
공통점
- 구조 기반 타입 : 객체가 필요한 메서드나 속성을 가지고 있으면 그 객체는 특정 타입으로 간주 ( 구조를 기준으로 타입 결정 )
- 유연성 : 객체의 구조만을 검사하기 때문에 코드의 유연성 증가
덕 타이핑: 특정 메서드나 속성을 가지면 그 타입으로 간주합니다. 타입을 명시적으로 선언하지 않음
구조적 타이핑: 타입의 구조가 일치하면 타입이 같다고 간주합니다. 인터페이스나 클래스를 통해 타입을 정의

차이점 
- 타입 선언 시점
덕타이핑 : 런타임 시 타입 수행
구조적타이핑 : 코드 작성 시점에 명시적으로 선언

- 타입 시스템
덕타이핑 : 자바스크립트에서 동적 타입 시스템을 가지고있어 변수의 타입이 실행 중에 동적으로 결정
구조적타이핑 : 타입스크립트에서 정적 타입 시스템을 가지고있어 컴파일 시에 수행되어 코드의 타입오류를 미리 발견 가능

- 타입 안전성
덕타이핑 : 런타임에 오류가 발견 되고 타입 관련 오류가 코드 실행 중에 나타날 수 있음
구조적타이핑 : 컴파일 시 타입 검사를 통해 타입 안정성이 향상되어 사전에 방지 가능

- 인터페이스와 타입 선언
덕타이핑 : 타입 선언을 위한 명시적인 문법이 없음, 객체의 구조에 의해 타입이 결정
구조적타이핑: 인터페이스나 타입 별칭을 통해 명시적으로 정의 가능

**Comment by Clt689** [comment]
## 차이점
### 1. 언어 차원에서의 지원
- 덕 타이핑: 자바스크립트와 같은 동적 타입 언어에서 주로 사용됩니다. 자바스크립트는 런타임에 객체의 속성과 메서드를 확인하고, 이에 따라 객체의 타입을 결정합니다. 즉, 덕 타이핑은 컴파일 시점이 아닌 런타임에 이루어집니다.
- 구조적 타이핑: 타입스크립트와 같은 정적 타입 언어에서 사용됩니다. 타입스크립트는 컴파일 시점에 객체의 구조를 분석하여 타입 검사를 수행합니다. 타입스크립트의 구조적 타이핑은 컴파일 타임에 타입 안정성을 제공하며, 타입 추론이 이루어집니다.

### 2. 타입 검사 시점
- 덕 타이핑: 런타임에 타입이 결정됩니다. 객체가 올바른 속성이나 메서드를 가지는지는 코드가 실행될 때 확인되며, 잘못된 속성이나 메서드에 접근하려고 하면 런타임 오류가 발생할 수 있습니다.-- 구조적 타이핑: 컴파일 타임에 타입이 결정됩니다. 타입스크립트는 코드가 실행되기 전에 객체가 올바른 구조를 가지고 있는지 확인하여, 타입 오류를 컴파일 단계에서 잡아낼 수 있습니다.

### 3. 타입 안정성
- 덕 타이핑: 런타임에서 타입 오류가 발생할 가능성이 있습니다. 코드를 작성하는 동안 타입이 일치하는지 명시적으로 확인되지 않기 때문에, 잘못된 타입이 런타임에서 오류를 발생시킬 수 있습니다.
- 구조적 타이핑: 컴파일 타임에 타입 검사가 이루어지므로, 잘못된 타입 사용으로 인한 오류를 사전에 방지할 수 있습니다. 이는 코드의 안정성을 높여줍니다.

### 4. 언어의 특징
- 덕 타이핑: 동적 언어에서는 타입이 명시적으로 정의되지 않으며, 코드가 실행되는 도중에 변수의 타입이 결정됩니다.
- 구조적 타이핑: 정적 언어에서는 타입이 명시적으로 정의되며, 코드를 작성할 때부터 타입을 알고 있거나 추론할 수 있어야 합니다. 타입스크립트는 구조적 타이핑을 사용하여, 컴파일 시점에 타입이 결정되도록 합니다.

## 결론
### 차이점
: 덕 타이핑은 런타임에 이루어지는 반면, 구조적 타이핑은 컴파일 타임에 이루어집니다. 덕 타이핑은 주로 동적 언어에서 사용되며, 구조적 타이핑은 정적 언어에서 사용되어 타입 안정성을 보장합니다.
