### ISSUE TITLE
4.1.2 타입스크립트의 합집합과 교집합

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#18]
📝 122p~125p

❓ 타입스크립트의 합집합과 교집합
책에서 유니온 타입과 교차 타입을 각각 합집합과 교집합으로 비유하였습니다.
어떻게 합집합과 교집합으로 비교되었는지 자신이 이해한 방식으로 설명해주세요!

**Comment by BaekWeb** [comment]
유니온타입 = 합집합

```ts
interface CookingStep {
	orderId: string;
	price: number;
}

interface DeliveryStep {
	orderId: string;
	time: number;
	distance: string;
}

function getDeliveryDistance(step: CookingStep | DeliveryStep) {
	return step.distance;
	// distance 는 DeliveryStep 에만 있다. 그렇기 때문에 타입 오류 발생
}

// 즉, CookingStep 에도 있고 DeliveryStep 에도 있을떄 접근이 가능하다.
```


교차타입 = 교집합


```ts
interface CookingStep {
	orderId: string;
	price: number;
}

interface DeliveryStep {
	orderId: string;
	time: number;
	distance: string;
}

function getDeliveryDistance(step: CookingStep & DeliveryStep) {
	return step.distance;
	// distance 는 DeliveryStep 는 오류가 나지 않는다.
}

// 기존의 타입을 하나로 합쳐 새로운 타입을 만드는 것

```

**Comment by gwangminjun** [comment]
### 유니온 타입
여러 타입중 하나를 가질수 있는 타입 <br>
 A | B는 A 타입이거나 B 타입 중 하나를 의미 <br>

 **합집합**은 **두 집합에 속하는 모든 원소**를 포함하는 집합 <br>
 유니온 타입은 각 타입의 모든 가능한 값을 **포함할 수 있는 타입**이기 때문에 합집합으로 표현한거 같습니다

 다만 합해질때 **공통되지 않는 속성은 제외**되기에 주의해야합니다.

### 교차 타입
여러 타입의 모든 특성을 동시에 가지는 타입<br>
교차 타입 A & B는 A 타입과 B 타입의 모든 특성을 동시에 만족하는 타입 <br>

**교집합**은 **두 집합에 모두 속하는 원소**만을 포함하는 집합 <br>
교차 타입은 **여러 타입의 공통된 속성만을 포함하는 타입**이므로 교집합으로 표현한거 같습니다

다만 합해질때 **공통되지 않는 속성도 포함**되기에 주의해야합니다.

**Comment by hyeonseong2023** [comment]
## 타입스크립트와 수학적 의미로서의 비교

### 1. 유니온 타입(합집합)
a. 수학적 의미: 두 집합의 모든 요소
b. 타입스크립트에서의 의미: 'A | B' 의 타입에서  A 타입이거나 B 타입인 값을 의미

=> 타입의 가능한 모든 경우의 '합'을 나타내지만, 값을 사용할 때는 타입 안정성의 보장으로 인해 
공통으로 접근 가능한 속성만이 가능


### 2. 교차 타입
a. 수학적 의미: 두 집합의 공통 요소
b. 타입스크립트에서의 의미: 'A & B' 의 타입에서 두 타입의 모든 속성을 갖는 타입

=> 두 요구사항을 모두 충족하는 객체 타입이 됨

---

### 1. 값의 합집합: 하나의 값을 가질 수 있는 모든 가능성을 포함하는 타입
```js
// user는 employee가 될 수도, manager가 될 수도 있다
type user = "employee" | "manager";
```

### 2. 값이 가진 속성의 합집합: 주어진 타입들이 모두 가지는 속성의 집합
```js
type employee = { name: string; department: string };
type manager = { name: string; age: number };

type user = "employee" | "manager";
// user는 값의 합집합으로 인해 employee가 될 수도, manager가 될 수도 있으나 age 외의 속성에는 접근할 수 없다
```
=>그렇기 때문에 값의 집합은 가능하지만 속성의 집합은 불가능
