### ISSUE TITLE
4.2.2 타입 가드 중 typeof, instanceof 연산자의 차이는 무엇인가요?

### ISSUE THREAD

**Issue by db-jay** [Gwangju-Web-Study/WoowahanTS_Study#21]
📝 p 134-135

❓ 타입가드란 런타임에 조건식을 사용하여 타입을 검사하고 타입 범위를 좁혀주는 기능을 말합니다.
`typeof` `instanceof` 연산자를 활용하여 타입을 분기 처리할 때의 각 특징은 무엇이 있을까요?

**Comment by hyeonseong2023** [comment]
### typeof
* 자바스크립트 타입 시스템에서만 대응 가능하며, 복잡한 타입에서는 한계가 존재
* 원시 타입: string, number, boolean, undefined, bigint, sysbol
* 객체 타입: object

### instanceof
* 객체가 특정 클래스나 생성자의 인스턴스인지 판별
* A instanceof B에서 A의 프로토타입 체인에 생성자 B의 프로토타입이 존재하는지 검사하여 boolean 값을 반환
* B에 올 수 있는 것은 클래스, 생성자 함수, DOM 요소, 내장 객체(Array, Date 등)이 있다.

=> 간단한 원시 타입 판별은 typeof, 커스텀 타입 및 확장된 타입 검사는 is 함수, 인스턴스 객체 타입의 요소 검사는 instanceof

**Comment by db-jay** [comment]
### typeof

- `typeof` 연산자는 원시타입(primitive types)을 확인할 때 주로 사용.
- 런타임에 값의 타입을 문자열로 반환하며, 기본적으로 원시 타입을 구분.
(`string`, `number`, `boolean`, `symbol`, `undefined`, `object`, `function`)
- 객체(object)타입을 정확히 검사할 수 없으므로 주의.

### instanceof

- 클래스나 생성자 함수로 생성된 객체에 대해 타입 가드 실행.
- 상속된 클래스들도 검사 가능. (프로토타입 체인 확인)

```tsx
class Book {
  constructor(public title: string) {}
}

class Video {
  constructor(public title: string) {}
}

function processStudyMaterial(material: string | Book | Video) {
  if (typeof material === 'string') {
    console.log(`string: ${material}`);
  } else if (material instanceof Book) {
    console.log(`Studying from the book: ${material.title}`);
  } else if (material instanceof Video) {
    console.log(`Watching the video: ${material.title}`);
  }
}

processStudyMaterial("TypeScript");
processStudyMaterial(new Book("TypeScript Handbook"));
processStudyMaterial(new Video("TypeScript Basics"));

// string: TypeScript
// Studying from the book: TypeScript Handbook
// Watching the video: TypeScript Basics
```

**Comment by gwangminjun** [comment]
## typeOf 연산자
- 변수의 기본타입(원시 타입) 을 확인
```ts
function printLength(x: string | number) {
  if (typeof x === "string") {
    console.log(x.length); // string 타입으로 좁히기
  } else {
    console.log(x.toFixed(2)); // number 타입으로 좁히기
  }
}
```

## instanceOf 연산자
- 객체가 특정 클래스나 생성자 함수의 인스턴스인지 확인
```ts
class Animal {
  move() {}
}
class Dog extends Animal {
  bark() {}
}

function performAction(animal: Animal) {
  if (animal instanceof Dog) {
    animal.bark(); // Dog 타입으로 좁히기
  } else {
    animal.move(); // Animal 타입으로 좁히기
  }
}
```

## 주요 차이점
- 대상
    - typeOf : 기본타입(원시 타입)
    - instanceOf : 특정 클래스나 객체
- 반환값
    - typeOf : 문자열
    - instanceOf : 불리언
- 동작방식
    - typeOf : 값의 타입을 직접 확인
    - instanceOf : 프로토타입 체인을 확인

**Comment by BaekWeb** [comment]
[용도]
typeof: 원시 타입 판별
instanceof: 객체의 인스턴스 여부 판별

[반환 값]
typeof: 문자열
instanceof: 불리언

[지원하는타입]
typeof: 원시 타입 (string, number, boolean, symbol, undefined) 및 함수
instanceof:  사용자 정의 객체 및 기본 객체 (Object, Array, Function 등)

[typeof의 특징]
```ts
// 주어진 값의 타입을 검사하는 함수
function checkType(value) {
    // value의 타입이 문자열인지 확인
    if (typeof value === "string") {
        // 문자열일 경우 실행
        console.log("문자열입니다.");
    } 
    // value의 타입이 숫자인지 확인
    else if (typeof value === "number") {
        // 숫자일 경우 실행
        console.log("숫자입니다.");
    } 
    // value의 타입이 함수인지 확인
    else if (typeof value === "function") {
        // 함수일 경우 실행
        console.log("함수입니다.");
    } 
    // 위의 조건이 모두 false일 경우 실행
    else {
        console.log("기타 타입입니다.");
    }
}

// 함수 사용 예시
checkType("hello"); // "문자열입니다."
checkType(42);      // "숫자입니다."
checkType(() => {}); // "함수입니다."
checkType(null);    // "기타 타입입니다."
```

[instanceof의 특징]
```ts
// Animal 클래스 정의
class Animal {}

// Dog 클래스는 Animal 클래스를 상속받음
class Dog extends Animal {}

// Dog 클래스의 인스턴스 생성
let dog = new Dog();

// dog가 Dog의 인스턴스인지 검사
if (dog instanceof Dog) {
    // dog가 Dog의 인스턴스일 경우 실행
    console.log("Dog의 인스턴스입니다.");
} 
// dog가 Animal의 인스턴스인지 검사
else if (dog instanceof Animal) {
    // dog가 Animal의 인스턴스일 경우 실행
    console.log("Animal의 인스턴스입니다.");
} 
// 위의 조건이 모두 false일 경우 실행
else {
    console.log("기타 타입입니다.");
}
```

[요약]
typeof 는 변수의 기본 데이터 타입을 확인할 때 유용하고 원시 타입에 대한 정보를 제공하지만 객체를 구분할 수 없는 한계가 있다.
instanceof 는 객체가 특정 클래스나 생성자의 인스턴스인지 판단할때 사용하고 객체 지향 프로그래밍에서 클래스 간의 관계를 확인

**Comment by db-jay** [comment]
수고하셨습니다! 죄송합니다
