### ISSUE TITLE
6.3.1 tsconfig.json 중 타입스크립트와 관련된 옵션에는 무엇이 있을까요?

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#26]
📝 p192
❓ tsconfig.json 파일은 프로젝트를 컴파일하는 데 필요한 루트 파일과 컴파일러 옵션을 지정하는 중요한 파일입니다.
tsconfig.json에는 수많은 컴파일 옵션을 지정할 수 있는데요, 여기서 타입과 관련된 옵션 중 일부를 소개해주세요.

**Comment by db-jay** [comment]
```tsx
// 어떤 버전의 js로 컴파일할지 설정
{
  "compilerOptions": {
    "target": "es2016", // ECMAScript 버전 지정
    "module": "commonjs", // 모듈 시스템
    "esModuleInterop": true, // CommonJS 모듈을 ES6 모듈 방식으로 import
    "forceConsistentCasingInFileNames": true, //파일 이름의 대소문자를 일관되게 사용
    "strict": true, //모든 엄격한 타입-체킹 옵션을 활성화
    "skipLibCheck": true, // (.d.ts) 파일의 타입 체크를 건너뜀
    "lib": ["dom", "dom.iterable", "esnext"], // 빌드할 때 포함할 라이브러리 목록
    "allowJs": true, // 자바스크립트 파일의 컴파일 허용
    "allowSyntheticDefaultImports": true, // default import를 사용할 수 있게 함
    "strictNullChecks": true, // null, undefined에 대한 엄격한 체크
    "noImplicitAny": true, // 암시적 any 타입을 허용하지 않음
    "moduleResolution": "Node", // 모듈 해석 방식
    "resolveJsonModule": true, // JSON 파일을 import 할 수 있게 함
    "isolatedModules": true, // 각 파일을 독립적인 모듈로 취급
    "noEmit": true, // 컴파일된 파일을 생성하지 않음
    "jsx": "react-jsx", // JSX 문법 사용
    "baseUrl": "./src", // 절대 경로를 사용하기 위한 기본 경로
    "paths": { // 절대 경로 별칭 설정
      "@/*": ["./*"] // @/로 시작하는 경로를 ./로 시작하는 경로로 변환
    }
  },
  "include": ["src", "src/types/*.d.ts"] // 컴파일할 파일 경로
}

```

**Comment by gwangminjun** [comment]
1. target: 생성할 자바스크립트 버전을 지정합니다. ('es5', 'es6', 'es2015' )
2. lib: 프로젝트에서 사용할 표준 라이브러리 파일을 지정합니다. ('dom', 'es6', 'dom.iterable')
3. strict: 엄격한 타입 검사 옵션을 활성화합니다. 'true'로 설정하면 null/undefined 체크, 엄격한 'this' 바인딩 등이 적용
4. noImplicitAny: 변수나 함수 매개변수의 타입을 명시적으로 지정하지 않으면 'any' 타입이 사용되는데, 이를 금지하는 옵션
5. strictNullChecks: null과 undefined 값의 사용을 엄격하게 검사하는 옵션
6. noUnusedLocals: 사용되지 않는 지역 변수를 허용하지 않도록 하는 옵션
7. noUnusedParameters: 사용되지 않는 함수 매개변수를 허용하지 않도록 하는 옵션
8. moduleResolution: 모듈 해석 방식을 설정합니다. 'node'로 설정하면 Node.js의 모듈 해석 방식을 따른다.

**Comment by hyeonseong2023** [comment]
1. declaration : 선언 파일(.d.ts) 생성
2. removeComments : 컴파일된 자바스크립트 파일에서 모든 주석 제거
3. outDir : 컴파일된 자바스크립트 파일이 생성될 디렉토리 지정
4. rootDir :  타입스크립트 소스 파일 루트 디렉토리를 지정

**Comment by BaekWeb** [comment]
noEmitOnError : 컴파일 중 오류가 발생하면 .js 파일을 생성하지 않도록 하는 옵션
코드 오류가 있을때 잘못된 자바스크립트 파일이 생성되고싶지 고싶을때 사용하며, 오류가 있는 js파일을 생성되지 않도록 하여 오류가 있는 상태로
배포되는 것을 방지

incremental : 컴파일 속도를 향상시키기 위해 변경된 파일만 다시 컴파일 ( 캐시 파일을 생성하여 이를 바탕으로 점진적 컴파일 ) 
큰 프로젝트에서 매번 전체 파일을 재컴파일하는 시간이 길어질 때 사용하며, 변경된 파일만 다시 컴파일하여 컴파일 속도를 향상

downlevelIteration : 구 버전의 자바스크립트(es3, es5)에서도 사용할 수 있도록 함
es3, es5를 지원하는 환경에서 for..of , spread 연산자 등을 사용하고싶을때 사용

sourceMap : 디버깅을 쉽게하기 위한 소스맵  파일 생성 
디버깅 할때, 컴파일된 js 파일이 아닌 원본 ts 파일과 연결하여 코드를 확인하고 싶을 때 사용
이를통해 브라우저 개발자 도구등에서 컴파일 된 자바스크립트 파일이 아닌 원본 ts 파일을 기반으로 디버깅 할수있다.
