### ISSUE TITLE
6.3. 타입스크립트 컴파일러의 주요 구성 요소들을 순서대로 나열하고, 각각의 역할을 간단히 설명하세요.

### ISSUE THREAD

**Issue by db-jay** [Gwangju-Web-Study/WoowahanTS_Study#27]
📝 192 -198p

❓ 아래 타입스크립트 컴파일러의 주요 구성 요소들을 순서대로 나열하고, 각각의 역할을 간단히 설명하세요.

```
a. 스캐너
b. 바인더
c. 파서
d. 이미터
e. 체커
```

**Comment by hyeonseong2023** [comment]
### a. 스캐너
* 타입스크립트 소스 파일을 어휘적으로 분석하여 **토큰**(의미 있는 작은 단위) 생성

⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬

### c. 파서
* 토큰 정보를 기반으로 **AST 생성**
> **AST**
컴파일러 핵심 자료 구조
소스코드의 구조를 트리 형태로 표현
최상위 노드는 타입스크립트 소스 파일 ↔️ 최하위 노드는 파일의 끝 지점

* 토큰 목록을 활용하여 실질적인 코드 구조를 노드 단위의 트리 형태로 표현

⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬

### b. 바인더
* AST에서 선언된 타입의 노드 정보를 저장하는 **심볼** 구조 생성
* 생성된 심볼과 그에 대응하는 AST 노드를 **연결**하는 역할 수행
=> 이로 인해 소스 코드의 구조(AST)와 의미(심볼)를 효율적으로 관리

⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬

### e. 체커
* AST의 노드를 탐색하면서 심볼 정보를 불러와 주어진 소스 파일에 대해 **타입 검사**를 진행
* 타입 검증 및 타입 에러에 대한 **에러 메시지 저장**

⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬

### d. 이미터
* 타입스크립트 소스 파일 **변환**(.ts or .tsx > .js or .jsx + .d.ts)

**Comment by db-jay** [comment]
![image](https://github.com/user-attachments/assets/9782925f-6a8b-4c55-8ee8-b3f3cb4fe23b)


### a. 스캐너 (Scanner)
소스코드를 의미있는 최소 단위인 ‘토큰’으로 분해합니다. (e.g. 키워드, 식별자, 리터럴, 연산자)
![image](https://github.com/user-attachments/assets/57538a6b-d7fa-4bb7-a9c2-fcf0ac1f33bf)


### c. 파서 (Parser)
토큰을 구문 트리(AST)로 변환하여 계층적 구조로 변환합니다.


### b. 바인더 (Binder)
AST를 분석하여 각 식별자(변수, 함수 등)에 대한 심볼을 생성하고, 이를 타입 정보와 연결합니다. 


### e. 체커 (Checker)
바인더가 생성한 심볼과 타입 정보를 사용하여 프로그램의 타입 정확성을 검사합니다. 
타입 불일치, 잘못된 사용 등의 오류를 찾아냅니다.

### d. 이미터 (Emitter)
타입 체크를 통과한 AST를 기반으로 목표 언어(대부분의 경우 JavaScript)의 코드를 생성합니다. 
이 과정에서 타입 정보는 제거되고, 순수한 JavaScript 코드가 출력됩니다.

**Comment by gwangminjun** [comment]
1. **스캐너(Scanner)**:
    - 입력 소스 코드를 토큰 단위로 분해하는 역할을 합니다.
    - 식별자, 숫자, 문자열 등의 토큰을 생성합니다.
    - 예시) 입력 코드 :  `let x: number = 42;`
   -  생성된 토큰: `let`, `x`, `:`, `number`, `=`, `42`, `;`

2. **파서(Parser)**:
    - 스캐너가 생성한 토큰들을 구문 분석하여 추상 구문 트리(Abstract Syntax Tree, AST)를 생성합니다.
    - AST는 코드의 구조와 의미를 표현하는 데이터 구조입니다.
   - 예시) 입력 코드 : `let x: number = 42;`
   - 생성된 AST:
    - AST의 Identifier 노드는 소스 코드에 나오는 변수, 함수, 클래스 등의 이름을 나타냅니다.
    - AST의 NumericLiteral 노드는 소스 코드에 나오는 숫자 리터럴을 나타냅니다.
     ```
     VariableStatement
       VariableDeclarationList
         VariableDeclaration
           Identifier(x)
           TypeAnnotation
             TypeReference(number)
           FirstAssignment
             NumericLiteral(42)
     ```

3. **바인더(Binder)**:
   - AST에 정의된 식별자들을 범위와 타입 정보에 바인딩합니다.
   - 식별자가 어디서 정의되었는지, 어떤 타입인지 결정합니다.
    - 예시) 입력 코드:
   ```typescript
   function calculateArea(width: number, height: number): number {
     return width * height;
   }
   ```
   - 변수 `width`, `height`, `return` 값이 바인딩됩니다.

4. **체커(Checker)**:
  - 바인딩된 타입 정보를 바탕으로 타입 검사를 수행합니다.
  - 타입 안전성을 확인하고, 오류를 감지하여 보고합니다.
  -  예시) 입력 코드:
   ```typescript
   let x: string = 42; // 오류: 'number' 형식은 'string' 형식에 할당될 수 없습니다.
   ```
   - 타입 불일치 오류가 감지됩니다.

5. **이미터(Emitter)**:
  - 타입 검사를 통과한 AST를 대상 코드(일반적으로 JavaScript)로 변환합니다.
  - 변환된 코드를 출력하여 최종 결과물을 생성합니다.
  - 예시) 입력 코드:
   ```typescript
   function add(a: number, b: number): number {
     return a + b;
   }
   ```
   - 출력 JavaScript 코드:
     ```javascript
     function add(a, b) {
       return a + b;
     }
     ```

**Comment by BaekWeb** [comment]
<img width="814" alt="스크린샷 2024-10-06 오후 3 13 22" src="https://github.com/user-attachments/assets/a4302bd0-9f4b-4839-a8e2-99c1ae085fdd">

1. 스캐너 - js 토큰화
-> 소스 코드를 문자열에서 토큰으로 변환하는 것으로 컴파일러가 소스 코드를 읽어들이고 코드의 의미를 최소단위인 토큰을 생성
토큰이란?: 키워드, 변수 이름, 리터럴(숫자나 문자열), 연산자 등 코드의 가장 작은 의미 단위

2. 파서 - 토큰 기반 AST 생성
-> 스캐너가 생성한 토큰 리스트를 분석하여 구문트리를 생성
-> 구문 트리는 코드의 구조를 계층적으로 나타냄

3. 바인더 - AST 노드 기반 심볼 생성
-> 구문 트리에서 변수, 함수, 클래스 등의 선언을 분석
-> 각 선언이 어느 스코프에서 유효한지 바인딩 ( 식별자가 어느 스코프에 속하는지 결정 )
스코프? : 변수가 유효한 범위를 나타냄
바인드? : 코드가 전역, 함수, 블록등 범위에 선언된  변수나 함수의 연결을 확인

4. 체커 - AST + 심볼 기반 타입검사
-> 바인더가 생성한 스코프와 선언 정보로 코드가 타입시스템에 맞는지 검사
-> 각 변수와 표현식이 올바른 타입을 가지고 있는지 확인

5. 이미터 - AST + 코드검사 기반 js 생성
-> 타입스크립트 코드 -> 자바스크립트 코드로 변환하여 출력
