### ISSUE TITLE
6.2 타입스크립트 컴파일러와 바벨

### ISSUE THREAD

**Issue by gwangminjun** [Gwangju-Web-Study/WoowahanTS_Study#28]
6.2 타입스크립트 컴파일러와 바벨
📝 p 191 타입스크립트 컴파일러와 바벨의 공통점 과 차이점은 어떤게 있을까요?

❓ 질문 타입스크립트 컴파일러와 바벨의 공통점 과 차이점에 대해서 기술해주세요!

**Comment by hyeonseong2023** [comment]
## 공통점
* ES5 이하의 자바스크립트 코드로 변환

## 차이점
* 타입스크립트 컴파일러: 타입을 검사
* 바벨: 자바스크립트 코드를 낮은 버전으로 ~컴파일~ 트랜스파일링

---

## 번외: 타입스크립트가 일부 바벨의 역할을 할 수 있음에도 둘을 함께 써야 하는 이유
1. 바벨의 유연성과 확장성
* 다양한 플러그인과 프리셋을 통해 매우 유연하게 구성
* 최신 JavaScript 기능, JSX, 타입스크립트 등 다양한 형태의 코드를 처리

2. 브라우저 호환성
* 바벨의 babel-preset-env를 사용하여 **지원해야 하는 특정 환경**에 맞춰 코드를 변환

3. 효율적인 플러그인
* @babel/preset-typescript를 통해 두 도구의 장점을 결합
  * 기존 순차적인 실행에 비해 단일 컴파일러로서 과정 단순화
  * 컴파일과 타입 체크를 분리할 수 있어, 개발 중에는 빠른 컴파일을, 필요할 때만 별도로 타입 체크를 수행
  
> 출처: https://ui.toast.com/weekly-pick/ko_20181220

**Comment by db-jay** [comment]
<h3>공통점</h3>
<ol>
<li>두 도구 모두 최신 ECMAScript 기능을 지원하고 이를 하위 버전의 JavaScript로 변환할 수 있습니다.</li>
<li>플러그인을 통해 변환 과정을 커스터마이즈할 수 있습니다.</li>
</ol>
<h3>차이점</h3>
<p>타입스크립트 컴파일러는 타입 안정성과 타입스크립트의 타입체크 기능에 중점을 두는 반면, 바벨은 다양한 자바스크립트 환경에서 호환성과 유연한 크로스브라우징에 초점을 맞춥니다.</p>

  | 타입스크립트 컴파일러 | 바벨
-- | -- | --
주요 기능 | TS를 JS로 변환하고 타입 체킹을 하는 것 | JS버전과 확장 문법을 지원하는 호환성 증대
타입 체킹 | 정적 타입 체크 기능 제공 | 기본적으로 타입 체크를 지원하지 않으며 플러그인을 통해 일부 지원 <br/>(@babel/preset-typescript) |  
입력 언어 | 주로 타입스크립트(.ts) 파일 처리 | js, ts, jsx 등 다양한 파일형식 처리

**Comment by gwangminjun** [comment]
**공통점:**
- 소스 코드를 변환하여 호환성 있는 코드로 만드는 역할을 한다.
- 최신 언어 기능을 구형 브라우저에서도 동작할 수 있게 해준다.
- 플러그인 기반으로 동작하여 확장성이 높다.

**차이점:**
- **목적**: 타입스크립트 컴파일러는 타입 검사와 타입 안전성을 제공하는 것이 주 목적이지만, 바벨은 주로 언어 기능 변환을 수행한다.
- **입력 언어**: 타입스크립트 컴파일러는 타입스크립트 코드를, 바벨은 자바스크립트 코드를 입력으로 받는다.
- **출력 언어**: 타입스크립트 컴파일러는 자바스크립트 코드를 출력하지만, 바벨은 더 낮은 수준의 호환성 있는 자바스크립트 코드를 출력한다.
- **타입 정보**: 타입스크립트 컴파일러는 타입 정보를 유지하지만, 바벨은 타입 정보를 제거한다.

**Comment by BaekWeb** [comment]
공통점 
코드 변환 : JavaScript로 코드를 변환

자바스크립트 코드 검증 : 변환 전후에 코드의 정확성을 검증 
 TypeScript - 주로 타입 검사를 통행 오류 발견
 Babel - 문법적인 오류를 탐지
 

차이점
타입검사
TypeScript: 코드 컴파일 시 타입 오류를 검사
Babel: 타입 검사를 지원하지 않음

구성파일
TypeScript: tsconfig.json 파일을 통해 다양한 컴파일러 옵션을 설정(타입 검사, 모듈 시스템 등)
Babel: babel.config.js 파일을 통해 변환 규칙과 플러그인 설정 관리( 주로 문법 변환과 플러그인 적용에 중점)

**Comment by gwangminjun** [comment]
수고하셨습니다!
