### ISSUE TITLE
6.1 자바스크립트의 고수준언어와 저수준언어

### ISSUE THREAD

**Issue by BaekWeb** [Gwangju-Web-Study/WoowahanTS_Study#29]
📝 p 184
❓ 고수준 언어중 하나를 선택해서 장단점을 기술해주시고 저수준 언어인 "어셈블리어"에 대해 설명해주세요. ( 고수준 언어는 중복불가 )

**Comment by hyeonseong2023** [comment]
## 고수준 언어 - 자바스크립트😉
### 장점
* 자동으로 메모리 관리
* 인간 친화적인 문법
* 쉬운 유지보수
### 단점
* 비교적 높은 사양 요구
* 실행 시 인터프리터 및 JIT 컴파일 과정으로 인한 구동 지연 가능성
> JIT❓ : https://blog.cinntiq.synology.me/jit/
---

## 어셈블리어
* **어셈블리어**(assembly language) 또는 **어셈블러 언어**(assembler language)는 기계어와 일대일 대응이 되는 컴퓨터 프로그래밍의 저급 언어
* **컴퓨터 구조**에 따라 사용하는 기계어가 달라지며, 따라서 **기계어에 대응**되어 만들어지는 어셈블리어도 각각 다르게 된다.
(CPU, 메모리, 레지스터, 입출력 장치 등)
> 기계어 : 실제로 컴퓨터의 CPU가 읽어서 실행할 수 있는 0과 1로 이루어진 명령어의 조합

**Comment by db-jay** [comment]
## 고수준 언어 - 파이썬 💥

### 장점

1. 인간의 사고와 유사한 읽기 쉽고 간결한 문법을 사용합니다.
    
    ```tsx
    print("Hello, World!")
    ```
    
2. 다른 언어나 라이브러리에 쉽게 접근해 쉽게 연동 가능한 높은 확장성(이식성)을 가집니다.
3. 개발자 커뮤니티 활성화로 인한 풍부한 자료와 지원 (e.g. https://pypi.org/)을 활용할 수 있습니다.
4. 대표적인 파이썬 활용 사례
    1. 구글 : `C++` + `Python`
    2. 인스타그램 : `Django` + `Python`
    3. 스포티파이 : Python을 활용해 빌드되었으며, 백엔드의 80% 파이썬 작성
    4. 드롭박스 : 외부 오픈 소스 코드, 자체코드 100%  Python작성
    (파이썬 창시자인 귀도 반 로썸이 2012-2019 드롭박스 재직)

### 단점

1. 컴파일 언어에 비해 상대적으로 실행 속도가 느립니다.
2. GIL(Global Interpreter Lock) 멀티 스레딩 성능에 제한이 있습니다.
    1. 파이썬 인터프리터가 한 번에 하나의 스레드만 파이썬 바이트 코드를 실행할 수 있도록 제한하기 때문.
    2. 비동기 프로그래밍(asyncio)을 사용하여 우회 가능.
3. 주로 데스크톱 애플리케이션 개발에 사용되며 네이티브 모바일 앱 개발에는 한계가 있습니다.
4. 타입 체크가 런타임에 이루어져 잠재적 버그 발생 가능성이 있습니다.
    1. Python3.5부터 타입체커가 도입되어 일부 해결 가능.

## 어셈블리어

### 특징

1. 저수준 프로그래밍 언어로, 기계어와 1:1 대응되는 니모닉(기호)을 사용합니다.
    1. e.g.  "MOV"는 데이터 이동, "ADD"는 덧셈
2. 불필요한 오버헤드 없이 정확히 필요한 명령어만 사용하므로 프로그램 크기를 최소화할 수 있습니다.
3. 프로그래머가 모든 세부사항을 직접 문법을 통해 제어해야합니다.
    
    ```tsx
    section .text
        global _start
    
    _start:
        mov eax, 4          ; 시스템 콜 번호 (sys_write)
        mov ebx, 1          ; 파일 디스크립터 (stdout)
        mov ecx, message    ; 출력할 문자열의 주소
        mov edx, 13         ; 문자열 길이
        int 0x80            ; 커널 호출
    
        mov eax, 1          ; 시스템 콜 번호 (sys_exit)
        xor ebx, ebx        ; 종료 상태 0
        int 0x80            ; 커널 호출
    
    section .data
        message db 'Hello, World!', 10
    ```

**Comment by gwangminjun** [comment]
**어셈블리어 특징:**
- 프로세서의 기본 명령어를 직접 사용하는 저수준 언어
- 하드웨어와 매우 밀접한 관계를 가지고 있어 하드웨어 제어와 최적화에 유리
- 프로그램 크기와 실행 속도가 빠름
- 프로그래밍이 복잡하고 가독성이 낮음
- 플랫폼 의존성이 높아 이식성이 낮음

**어셈블리어 사용 사례:**
- 운영 체제 커널, 드라이버, 펌웨어 등 저수준 시스템 프로그래밍
- 고성능, 실시간 처리가 필요한 분야 (게임, 멀티미디어, 임베디드 시스템 등)
- 하드웨어 자원에 대한 정밀한 제어가 필요한 경우

**Comment by BaekWeb** [comment]
고수준 언어 - Ruby
장점
1. 간결한 문법 : 매우 간결한 문법을 가지고있어 코드를 읽고 쓰는데 직관적 Java나 C#보다 가독성이 높다.
2. 메타포로그래밍 기능 : 메타프로그래밍을 쉽게 할 수있어 코드 구조를 동적으로 변경하거나 새로운 구문을 생성 가능, 파이썬이나 자바와 비교할 때 상대적으로 좋음 

단점 
1. 메모리 사용량 : 메모리를 많이 소모하는 경향이 있다. 대규모 애플리케이션에서 성능 저하 발생 ( Java는 JVM의 최적화로 인해 상대적으로 메모리 관리가 효율적)

2. 비동기 처리의 어려움 : 비동기 처리를 구현하는 데 있어 복잡 (JavaScript의 Promise나 async/await 구문처럼 비동기 처리를 자연스럽게 사용하기 힘들다)

3. 상대적으로 낮은 채택률 : JavaScript나 Python에 비해 상대적으로 낮은 인기를 얻고있다


저수준언어 - 어쎔블리어
- 컴퓨터가 이해하기 쉬운 언어로 기계어를 영문자 기호로 치환한 언어
- 어셈블리어로 작성된 프로그램은 대체로 컴파일러 언어로 작성된 프로그램보다 실행속도가 빠르다.
- 프로그래머가 하드웨어와 직접소통 가능하다
