### ISSUE TITLE
8.3.2 React.ReactElement vs JSX.Element vs React.ReactNode 의 차이

### ISSUE THREAD

**Issue by gwangminjun** [Gwangju-Web-Study/WoowahanTS_Study#33]
📝 p 253

❓  React.ReactElement vs JSX.Element vs React.ReactNode 의 
1. 사용예시
2. 차이점
에 대해서 설명해주세요 ~

**Comment by gwangminjun** [comment]
## React.ReactElement, JSX.Element, React.ReactNode 비교

### 1. 사용 예시

**React.ReactElement**:
- `React.createElement()` 함수를 사용하여 **직접 React 엘리먼트를 생성**할 때 사용합니다.
- 서버 측 렌더링에서 **React 컴포넌트를 렌더링**할 때 사용됩니다.
- **동적으로 컴포넌트를 생성해야 할 때 활용**할 수 있습니다.

**JSX.Element**:
- **JSX 구문으로 선언된 React 엘리먼트**를 나타냅니다.
- 컴포넌트의 **props와 children을 정의**할 때 사용됩니다.
- 코드 분석과 리팩토링을 위해 **JSX로 표현된 엘리먼트를 구분할 때 유용**합니다.

**React.ReactNode**:
- **렌더링 가능한 모든 유형**(문자열, 숫자, 불리언, React 엘리먼트 등)을 나타냅니다.
- 주로 `children` props와 같이 **자식 노드를 표현**할 때 사용됩니다.
- 컴포넌트의 반환 값이나 렌더링 메서드에서 **다양한 유형의 노드를 허용할 때 사용**됩니다.

#### 1.1 React.ReactElement 동적 컴포넌트 생성예시
```typescript
import React from 'react';

// 동적으로 생성할 컴포넌트
const DynamicComponent: React.FC = () => {
  return (
    <div>
      This is a dynamically created component.
    </div>
  );
};

// 동적 컴포넌트 생성 함수
function createDynamicComponent(): React.ReactElement {
  return React.createElement(DynamicComponent, {});
}

// 사용 예시
const app = (
  <div>
    <h1>My App</h1>
    {createDynamicComponent()}
  </div>
);

ReactDOM.render(app, document.getElementById('root'));
```

- `createDynamicComponent` 함수를 사용하여 `DynamicComponent`를 동적으로 생성
- `React.createElement`를 사용하여 `DynamicComponent`의 React 엘리먼트를 생성하고, 이를 반환합니다.
- `app` 변수에서 동적으로 생성된 컴포넌트를 렌더링하고 있습니다.


동적 컴포넌트 활용예시
1. **조건부 렌더링**: 특정 조건에 따라 **다른 컴포넌트를 렌더링**해야 할 때
2. **플러그인 아키텍처**: **동적으로 플러그인을 로드하고 활성화**해야 할 때
3. **UI 편집기**: **사용자가 UI를 실시간으로 편집**할 수 있는 경우


#### 1.2 JSX.Element  엘리먼트를 구분예시

```typescript
interface MyComponentProps {
  children: JSX.Element;
}

const MyComponent: React.FC<MyComponentProps> = ({ children }) => {
  return (
    <div className="my-component">
      {children}
    </div>
  );
};

// 사용 예시
<MyComponent>
  <div>This is a JSX-based element.</div>
</MyComponent>
```
`MyComponent`의 `children` props는 `JSX.Element` 타입으로 정의되어, 
**오직 JSX로 표현된 React 엘리먼트만 허용**됩니다.  타입 안전성이 향상


#### 1.3 React.ReactNode 다양한 유형의 노드를 허용할 때 사용예시

```typescript
import React from 'react';

interface WrapperProps {
  children: React.ReactNode;
}

const Wrapper: React.FC<WrapperProps> = ({ children }) => {
  return (
    <div className="wrapper">
      {children}
    </div>
  );
};

// 사용 예시
const App: React.FC = () => {
  return (
    <Wrapper>
      <h1>Hello, World!</h1>
      <p>This is some content.</p>
      {/* React 엘리먼트도 children으로 전달 가능 */}
      <button>Click me</button>
    </Wrapper>
  );
};
```


- `Wrapper` 컴포넌트의 `children` props는 `React.ReactNode` 타입으로 정의
- `Wrapper`에는 문자열, 숫자, 불리언, React 엘리먼트 등 다양한 유형의 자식 노드를 전달가능


### 2. 차이점

1. **표현 방식**:
   - `React.ReactElement`: **`React.createElement()`** 사용
   - `JSX.Element`: **JSX 구문** 사용
   - `React.ReactNode`: **모든 렌더링 가능한 유형**

2. **유형 범위**:
   - `React.ReactElement`: **React 엘리먼트의 기본 자료형**
   - `JSX.Element`: **`React.ReactElement`의 하위 집합**
   - `React.ReactNode`: 가장 광범위한 유형, **모든 렌더링 가능한 유형 포함**

3. **처리 과정**:
   - `React.ReactElement`: **런타임**에 해석되고 처리됨
   - `JSX.Element`: **컴파일 타임**에 **`React.createElement()` 호출로 변환**됨
   - `React.ReactNode`: 다양한 유형의 값을 허용하므로 **런타임에 처리**됨

4. **타입 안전성**:
   - `JSX.Element`: **`React.ReactElement`의 하위 집합이므로 더 안전**함
   - `React.ReactNode`: 가장 일반적이지만 **가장 낮은 타입 안전성**을 가짐

**Comment by db-jay** [comment]
![image](https://github.com/user-attachments/assets/e9d3371e-895a-42aa-b7db-fb234f839f45)


### React.ReactElement

- Virtual DOM 을 기반으로 렌더링하는 엘리먼트 형태.
- React 엘리먼트를 객체 형태로 저장하기 위한 타입.
- JSX의 `createElement()` 메서드가 반환하는 타입.
    
    ```tsx
    // 특정 HTML 엘리먼트만 허용하고 싶을 때 사용
    interface ButtonWrapperProps {
      button: React.ReactElement<HTMLButtonElement>; // button 엘리먼트만 허용
    }
    
    const ButtonWrapper: React.FC<ButtonWrapperProps> = ({ button }) => {
      return (
        <>
          {button}
        </>
      );
    };
    
    // 사용 예시
    const App = () => {
      return (
        <ButtonWrapper 
          button={<button onClick={() => alert('클릭')}>클릭하세요</button>} 
        />
      );
    };
    ```
    

### JSX.Element

- ReactElement를 확장하고 있는 타입.
- `React.ReactElement<any, any>`와 동일.
- JSX 문법으로 생성된 엘리먼트를 의미함.
    
    ```tsx
    declare global {
    	namespace JSX {
    		interface Element extends React.ReactElement<any, any> {}
    	}
    }
    ```
    

### React.ReactNode

- 단순히 ReactElement외에도 boolean, string, number등의 여러 타입을 포함.
- 리액트 컴포넌트가 가질 수 있는 모든 타입을 포함.
- prop으로 리액트 컴포넌트가 다양한 형태를 가지도록 할 때 사용.
    
    ```tsx
    interface ContainerProps {
      children: React.ReactNode;
      header?: React.ReactNode;
      footer?: React.ReactNode;
    }
    
    const Container: React.FC<ContainerProps> = ({ children, header, footer }) => {
      return (
        <div className="container">
          {header && <div className="header">{header}</div>} 
          <div className="content">{children}</div>
          {footer && <div className="footer">{footer}</div>}
        </div>
      );
    };
    
    // 다양한 타입의 컨텐츠 허용
    const App = () => {
      return (
        <Container
          header="안녕하세요" /* string */
          footer={<p>푸터 텍스트입니다</p>} /* ReactElement */
        >
          <h1>제목</h1>
          {"텍스트입니다"}
          {42}
          {true && <p>조건부 렌더링</p>}
          {[1, 2, 3].map(num => <span key={num}>{num}</span>)}
        </Container>
      );
    };
    ```

**Comment by hyeonseong2023** [comment]
## React.ReactElement
* createElement()가 반환하는 구체적인 React 엘리먼트 타입
* props와 type이 명확하게 지정된 불변(immutable) 객체
* Virtual DOM의 가장 기본적인 빌딩 블록

## JSX.Element
* React.ReactElement의 특수한 케이스로, **JSX 문법**으로 작성된 엘리먼트
* type 속성이 문자열이나 React 컴포넌트로 제한
* TypeScript에서 JSX 문법을 사용할 때 기본적으로 사용되는 타입

## React.ReactNode
* **render()가 반환할 수 있는 모든 것**을 포함
* string, number, boolean, null, undefined, React.ReactElement 등을 **모두 포함**
* children prop의 타입으로 자주 사용되며, 다양한 타입의 자식 요소를 허용

```jsx
// React.ReactElement 예시
const reactElement1 : React.ReactElement = <div>Hello</div>;
const ReactElement2 : React.ReactElement = <Button>Click</Button>;
// const ReactElement3 : React.ReactElement = "text";       // ❌ 문자열 불가
// const ReactElement4 : React.ReactElement = 1103;        // ❌ 숫자 불가
// const ReactElement5 : React.ReactElement = true;         // ❌ boolean 불가

// JSX.Element 예시
const jsxElement: JSX.Element = reactElement1;             // ✅ ReactElement 가능
const jsxElement2: JSX.Element = <div>Hello</div>;     // ✅ JSX 가능
// const jsxElement3: JSX.Element = "text";                     // ❌ 문자열 불가
// const jsxElement4: JSX.Element = 1103;                      // ❌ 숫자 불가

// React.ReactNode 예시
const reactNode1: React.ReactNode = reactElement1;           // ✅ ReactElement 가능
const reactNode2: React.ReactNode = jsxElement2;               // ✅ JSX 가능
const reactNode3: React.ReactNode = "text";                         // ✅ 문자열 가능
const reactNode4: React.ReactNode = 1103;                          // ✅ 숫자 가능
const reactNode5: React.ReactNode = true;                           // ✅ boolean 가능
const reactNode6: React.ReactNode = null;                            // ✅ null 가능
const reactNode7: React.ReactNode = undefined;                  // ✅ undefined 가능
```

**Comment by gwangminjun** [comment]
수고하셨습니다.!
