### ISSUE TITLE
9.1.2. useEffect의 인자 effect와 deps에 대해 설명해주세요. 

### ISSUE THREAD

**Issue by db-jay** [Gwangju-Web-Study/WoowahanTS_Study#38]
📝 p290

❓ 질문
랜더링 이후 리액트 함수 컴포넌트에 어떤 일을 수행해야 하는지 알려주기 위해 useEffect훅을 사용할 수 있습니다. useEffect의 인자 effect와 deps에 대해 설명해주세요.

**Comment by hyeonseong2023** [comment]
## uesEffect 타입 정의
```ts
function useEffect(effect: EffectCallback, deps?: DependencyList): void;
```
## 1. effect
* EffectCallback 타입
* Destructor를 반환하거나 아무것도 반환하지 않는다.
```ts
type EffectCallback = () => void | Destructor;
```
>💡Destructor(클린업 함수)
> ```ts
> useEffect(() => {
>  // 작업
>  return () => {
>    // 클린업 작업
>  };
> });
> ```
> return으로 반환되는 함수

## 2. deps
* **옵셔널**하게 제공
* effect가 수행되기 위한 **조건**을 나열
* deps의 변경 여부를 **얕은 비교**로만 판단하기 때문에, **실제 사용하는 값**을 사용할 것
```ts
type DependencyList = ReadonlyArray<any>;
```
* deps 배열에 따른 실행 패턴
  1. deps 배열이 없는 경우 -> 컴포넌트가 리렌더링될 때마다 실행
  2. deps 배열이 비어있는 경우 -> 컴포넌트가 처음 렌더링될 때만 실행
  3. deps 배열에 값이 있는 경우 -> 배열의 값이 변경될 때마다 실행

> 💡deps는 ReadonlyArray인데 deps 배열의 값이 변경될 수 있는가
> * deps는  배열 구조의 불변성을 보장
> * 그러나 값을 직접 갖고 있는 게 아니라 '참조'를 갖고 있기 때문에 값들의 변경은 제한하지 않음

**Comment by gwangminjun** [comment]
`useEffect`의 주요 인자

1. **effect**: 
   - 이 인자에는 실제로 수행할 사이드 이펙트 함수가 전달됩니다.
   - 이 함수 내부에서 데이터 가져오기, 구독 설정, 수동 DOM 조작 등의 작업을 수행할 수 있습니다.
   - 필요한 경우 이 함수에서 클린업 함수를 반환할 수 있습니다. 이 클린업 함수는 컴포넌트가 언마운트될 때 실행되어 리소스를 정리할 수 있습니다.

```ts
  useEffect(() => {
    // 데이터 가져오기
    async function fetchData() {
      const response = await fetch('/api/data');
      const data = await response.json();
      setData(data);
    }
    fetchData();
    // 언마운트 시 정리 작업
    return () => {
      // 구독 해제, 타이머 정지 등의 작업 수행 
      // 클린업 함수 Destructor
      console.log('MyComponent is unmounting');
    };
  }, []);
```

2. **deps**:
   - 이 인자에는 effect 함수에 전달된 값들의 의존성 배열이 전달됩니다.
   - 이 배열에 포함된 값들이 변경되면 effect 함수가 다시 실행됩니다.
   - 빈 배열 `[]`을 전달하면 마운트 시에만 effect 함수가 실행되고, 그 이후에는 실행되지 않습니다.
   - 만약 deps 배열을 생략하면 effect 함수가 매 렌더링 시마다 실행됩니다.

```ts
useEffect(() => {
  // name 값이 변경되면 실행됨
  console.log(`내 이름은 ${name}`);
}, [name]);
```

이런 식으로 `useEffect`를 통해 컴포넌트의 라이프사이클 메서드를 관리하고 필요한 사이드 이펙트를 수행할 수 있습니다.

**Comment by db-jay** [comment]
> `useEffect` 는 React의 생명주기를 함수형 컴포넌트에서 다룰 수 있게 해주는 핵심적인 Hook. `effect`와 `deps`를 올바르게 이해하고 사용하는 것은 컴포넌트의 성능과 안정성에 매우 중요함.
> 

### effect

- 수행할 작업을 정의하는 함수
- effect 함수는 선택적으로 cleanup 함수를 반환할 수 있음

```tsx
useEffect(() => {
  // 1. 렌더링 이후 실행되는 코드
  console.log('effect 실행');

  // 2. 선택적 cleanup 함수 반환
  return () => {
    console.log('cleanup 실행');
  };
}, []); // deps 배열
```

### deps

- effect가 의존하는 값들의 배열 (선택적)
    - 빈 배열 `[]`: 마운트/언마운트 시에만 실행
    - 배열 생략: 매 렌더링마다 실행
    - 값이 있는 배열: 해당 값들이 변경될 때만 실행

```tsx
// 1. 타이틀 업데이트
useEffect(() => {
  document.title = `${count} 번 클릭됨`;
}, [count]);

// 2. API 호출
useEffect(() => {
  fetchData();
}, [searchUserName]);

// 3. 구독 설정/해제
useEffect(() => {
  const subscription = subscribe();
  return () => subscription.unsubscribe();
}, []);
```
