### ISSUE TITLE
1.1.4_CBD 방법론의 등장 배경과 장점은 무엇인가요?

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#4]
📝 24p

❓ CBD(Component Based Development) 방법론은 어떻게 등장하게 되었고, 해당 방식의 장점에는 어떤 것들이 있을까요? 😶

**Comment by Clt689** [comment]
### CBD 방법론 등장 배경
웹 어플리케이션 서비스의 규모가 커지면서 웹 페이지를 통으로 만드는 방식의 개발이 아닌, 컴포넌트 단위의 개발이 필요해짐. 

---
### CBS 방법론의 장점
- 데이터마다 목적에 맞게 구분하고 이에 적절한 UI를 표현할 수 있음
- 하나의 독립된 기능을 재사용할 수 있음

**Comment by BaekWeb** [comment]
객체지향 방법론은 코드 수준의 재사용인 반면 이것을 보완하기 위해 CBD 방법론인 컴포넌트 조립 방식으로 모듈까지 재사용성을 높이기 위해 입니다.

**Comment by gwangminjun** [comment]
1. CBD 방법론의 등장 배경
기존의 소프트웨어 개발 방법론은 
대부분 모놀리식(monolithic) 개발 방식을 사용
모놀리식(monolithic)
: 모놀리식(monolithic) 개발 방식은 소프트웨어를 전체적으로 하나의 큰 모듈로 개발하는 방식

모놀리식 방식의 문제점
1. 소프트웨어가 복잡해질수록 유지보수가 어렵고, 기능 추가나 변경이 어려움.
2. 소프트웨어 전체의 장애나 버그가 발생 시, 시스템 전체가 영향을 받아 전체적인 안정성이 낮아지는 문제점.

CBD는 이러한 문제점들을 해결하기 위해 소프트웨어를 재사용 가능한 컴포넌트로 분해하여 개발하는 방식을 제안


2.객체 지향 방법론 과의 차이점
객체지향 방법론은 코드 수준에서 재사용 ,
CBD 방법론은 실행 모듈 단위로 재사용


4. 컴포넌트 방법론의 장점
소프트웨어를 재사용 가능한 컴포넌트로 분해하여 개발하는 방식
개발 기간 단축
개발 비용 단축
시스템의 유지보수성 향상
시스템의 품질 향상

5. 컴포넌트 방법론 핵심
재사용성과 유지보수 용이성
각 컴포넌트가 재사용 가능하며, 독립적으로 테스트할 수 있어야 한다.

6.리액트와의 연관성
SPA(Single Page App.)는 CBD(Component Based Dev.)를 
기반으로 하고 있고, 리액트는 SPA를 위한 라이브러리이니, 
결론은 리액트가 객체 지향 방법론 중에서 컴포넌트 베이스 개발 방법론으로 만들어졌다는 것

참조
https://velog.io/@ainochi95/20m-CBDComponent-Based-Development
https://blog.naver.com/jvioonpe/220246549818
