### ISSUE TITLE
10.2 상태 관리 라이브러리를 선택하는 기준

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#40]
📝 p324

❓ 상태 관리 라이브러리를 선택하는 기준
우형 이야기에서 각자의 상황에 맞는 상태 관리 라이브러리를 선택하는 내용이 등장합니다.
(1)이전에 진행했던 프로젝트나 앞으로 진행하고자 하는 프로젝트에 어울리는 상태 관리 라이브러리를 선택해주시고, 
(2)다른 라이브러리와 비교하여 선택한 이유를 설명해주세요!

**Comment by hyeonseong2023** [comment]
### 선택 흐름도
0. 리액트를 사용하는 소규모 사이드 프로젝트 예정
1. 목표한 토스에서 주로 사용하는 TanStack Query, Recoil, Jotai 중에서 고려
2. TanStack Query는 금융 데이터 특성같이 서버 상태 관리에 최적화 되어있어 제외
3. Recoil과 Jotai는 둘 다 React스타일로 훅 사용법이 비슷하여 러닝 커브가 적음
4. 그러나 Recoil은 기능이 더 많으며, 현재 실험 단계임
5. Jotai는 가볍고 사용하기 단순하며 추후 대규모 프로젝트로 확장되더라도 Recoil로 마이그레이션 하기 좋음
```jsx
// Recoil
import { RecoilRoot, atom, useRecoilState } from 'recoil'
// 1. RecoilRoot
function App() {
  return (
    <RecoilRoot>
      <Counter />
    </RecoilRoot>
  )
}
// 2. Unique Key
const countState = atom({
  key: 'countState',
  default: 0
})
// Jotai
import { atom, useAtom } from 'jotai'
// 1. Root 불필요
function App() {
  return <Counter />
}
// 2. 바로 생성
const countAtom = atom(0)
```

**Comment by db-jay** [comment]
### 1️⃣ 이전에 진행했던 프로젝트나 앞으로 진행하고자 하는 프로젝트에 어울리는 상태 관리 라이브러리?

- 이전 프로젝트에서 서버 데이터는 `TanstackQuery` 로 관리하고 클라이언트 데이터는 `Recoil` 을 사용했음.
- 현재 진행 중인 프로젝트에서는 `TanstackQuerey` 와 `ContextAPI`만 사용하고 있는데, 클라이언트 데이터 관리를 위해 `Zustand` 를 도입해 볼 예정임.

### 2️⃣ Zustand🐻 를 선택한 이유

1. 곰이 귀여움.
2. Zustand는 최근 업데이트가 활발하고, 가볍고 빠르게 사용할 수 있는 상태 관리 라이브러리로 큰 인기를 끌고 있음. 
3. Recoil은 Facebook이 개발했지만, 최근 2년간 유지보수가 부족한 상태이며, 다운로드 수와 커뮤니티 관심이 정체된 모습을 보이고 있음.
4. 2024년 11월 기준 npm trends 참고

    | 기준 | Zustand | Recoil |
    | -- | -- | -- |
    | 다운로드 트렌드 | 증가세, Recoil보다 인기 상승 | 다운로드 수 정체, 성장 둔화 |
    | Stars (GitHub) | 47,936 (높음) | 19,610 (낮음) |
    | 이슈 관리 | 매우 적은 이슈(4개)로 안정성 높음 | 높은 이슈 수(321개), 업데이트 부족 |
    | 업데이트 빈도 | 16일 전 (최근 업데이트) | 2년 전 (오랫동안 업데이트 없음) |
    | 설치 크기 | 86.5 KB (가벼움) | 2.2 MB (상대적으로 무거움)|

    ![image](https://github.com/user-attachments/assets/2349721d-965f-4a7e-b9f0-3d9a0f47f49c)
    
5. 라이브러리별 특징 비교

   | 라이브러리 | 강점 | 단점 | 주요 사용 사례 |
   | -- | -- | -- | -- |
   | Redux | 강력한 DevTools, 중앙 집중식 관리 | 보일러플레이트 많음 | 대규모 애플리케이션 |
   | Zustand | 가벼운 설정, 간단한 API | 상태 구조가 단순한 경우에 적합 | 중소규모 앱, 단순 상태 관리 |
   | Tanstack Query | 서버 상태 관리 특화 | 클라이언트 상태 관리에 부적합 | 비동기 데이터 관리 |
   | MobX | 반응형 상태 관리, 코드 간결성 | 상태 추적 및 디버깅 어려움 | 중소규모 앱, 빠른 설정 |
   | Recoil | React에 최적화, 상태 분할 용이 | 커뮤니티 및 확장성 부족 | React, atom 기반 관리 |

**Comment by gwangminjun** [comment]
## 하고자하는 소규모 프로젝트
- openlayers + react 조합 프로젝트 

## Redux 선택한 이유
- **Recoil** 
  - 분산 구조의 상태 관리 방식
  - Redux 생태계가 더 성숙하고 확장성이 높아, 복잡한 OpenLayers 애플리케이션 구현에서 더 유리
- **MobX** 
  - OpenLayers 애플리케이션에서는 지도 객체, 레이어, 인터랙션 등의 상태 변화를 명시적으로 추적해야함 
  - MobX는 상태 추적 및 디버깅 어려움이 어렵기때문에 제외
- **Zustand**
  - 상대적으로 간단한 API와 경량화된 설계
  - 지도, 레이어, 피처 등 많은 상태 정보를 체계적으로 관리해야하는 openlayers 와 부적합
- **Tanstack Query**
  - API 호출과 관련된 상태 관리에 초점
  - 많은 클라이언트단  상태 정보를 체계적으로 관리해야하는 openlayers 와 부적합


## Redux와 OpenLayers 통합
1. **지도 객체 관리**:
   - Redux 스토어에 지도 객체와 관련된 상태를 저장하고 관리합니다.
   - 지도 객체의 생성, 이동, 확대/축소 등의 작업을 Redux 액션으로 처리합니다.

2. **레이어 및 피처 관리**:
   - 지도에 추가되는 레이어와 피처 정보를 Redux 상태에 저장합니다.
   - 레이어 및 피처의 가시성, 스타일 등의 변경을 Redux 액션으로 처리합니다.

3. **사용자 인터랙션 관리**:
   - 사용자의 클릭, 드래그, 줌 등의 인터랙션을 Redux 액션으로 처리합니다.
   - 사용자 인터랙션에 따른 지도 객체, 레이어, 피처 등의 상태 변화를 관리합니다.

4. **디버깅 용이성**:
   - OpenLayers 애플리케이션에서는 지도 객체, 레이어, 인터랙션 등의 상태 변화를 추적하기 어려울 수 있습니다.
   - Redux의 Time Travel Debugging 기능을 통해 상태 변경 이력을 확인하고 디버깅할 수 있습니다.

**Comment by hyeonseong2023** [comment]
수고하셨슴다!!
