### ISSUE TITLE
10.1   React에서 SSOT 와 제어(Controlled)와 비제어(Uncontrolled) 컴포넌트

### ISSUE THREAD

**Issue by gwangminjun** [Gwangju-Web-Study/WoowahanTS_Study#41]
📝 309p

❓ React에서 SSOT 개념은 제어(Controlled)와 비제어(Uncontrolled) 컴포넌트의 개념과 밀접하게 연결되어 있다고 합니다.
이 두 가지 개념을 통해 SSOT를 어떻게 구현하고, 어떤 상황에서 사용하는지 설명해주세요

**Comment by hyeonseong2023** [comment]
## SSOT
* 하나의 상태로 통합 관리

## 제어 컴포넌트
* React의 **상태**를 사용하여 데이터를 관리
* 컴포넌트의 상태(state)를 업데이트하고, 이를 컴포넌트의 속성(props)로 전달하여 UI를 제어
* 사용자 입력에 대한 이벤트 핸들러를 통해 상태를 업데이트하고(onChange), 업데이트된 상태를 UI에 반영

* 보다 정교한 상태 관리와 유효성 검사를 위해 사용

## 비제어 컴포넌트
* React의 상태를 사용하지 않고,** DOM을 직접 조작**하여 데이터를 관리
* 컴포넌트가 자체적으로 상태를 가지지 않으며, 사용자 입력에 대한 DOM 이벤트를 직접 처리하여 데이터를 추출
* 사용자 입력에 대한 DOM 이벤트 처리기를 통해 데이터를 추출하고(ref), 필요에 따라 직접 상태를 업데이트하거나 다른 방식으로 데이터를 처리(onSubmit)

* React로 직접 제어하기 어려운 상황
* 단순한 상황 (실시간 유효성 검사나 즉각적인 UI 업데이트가 필요 없는 상황)에서 더 간편하게 사용

## 예시 코드
```jsx
// 비제어 컴포넌트 (SSOT 위반)
function UncontrolledComponent() {
 return (
   <form onSubmit={(e) => {
     e.preventDefault();
     console.log(e.target.name.value, e.target.age.value);
   }}>
     <input name="name" placeholder="이름" />
     <input name="age" placeholder="나이" />
     <button>제출</button>
   </form>
 );
}

// 제어 컴포넌트 (SSOT 준수)
function ControlledComponent() {
 const [user, setUser] = useState({ name: '', age: '' });
 
 const submit = () => {
   console.log(user.name, user.age);
 };

 return (
   <form onSubmit={submit}>
     <input 
       value={user.name}
       onChange={e => setUser({...user, name: e.target.value})}
     />
     <input 
       value={user.age}
       onChange={e => setUser({...user, age: e.target.value})}
     />
     <button>제출</button>
   </form>
 );
}
```

**Comment by db-jay** [comment]
## 1. 제어 컴포넌트(Controlled Component)

- 모든 상태는 React에서 관리하기 때문에, React 상태가 SSOT(Single Source of Truth)가 됨.
- 컴포넌트의 값과 동작이 React state에 의해 완전히 통제되며, 이에 따라 UI가 업데이트됨.
- e.g.  `<input>` 필드의 값을 상태로 관리하고, 상태가 업데이트될 때마다 `<input>`의 값도 함께 변경.
    
    ```tsx
    import { useState } from 'react';
    
    function ControlledInput() {
      const [value, setValue] = useState(''); // React 상태가 SSOT
    
      const handleChange = (event) => {
        setValue(event.target.value); // 상태 업데이트와 동시에 input의 값도 반영
      };
    
      return (
        <div>
          <input type="text" value={value} onChange={handleChange} />
          <p>Current Value: {value}</p>
        </div>
      );
    }
    ```
    

## 2. 비제어 컴포넌트(Uncontrolled Component)

- 비제어 컴포넌트는 컴포넌트 자체가 상태를 관리하며, React 상태와 연결되지 않는 경우를 의미함.
- 주로 ref를 사용하여 DOM 요소에 직접 접근해 값을 가져오거나 설정함.
- 비제어 컴포넌트에서는 DOM 자체가 SSOT 역할을 하며, React 상태를 사용하지 않음.
- e.g. `useRef`로 DOM 요소에 접근하여 React 상태를 거치지 않고 파일 데이터 처리.
    
    ```tsx
    import React, { useRef } from 'react';
    
    function FileInput() {
      const fileInputRef = useRef<HTMLInputElement>(null);
    
      const handleFileUpload = () => {
        if (fileInputRef.current?.files) {
          const file = fileInputRef.current.files[0]; // 선택된 첫 번째 파일
          console.log('Selected File:', file);
        }
      };
    
      return (
        <div>
          {/* 파일 입력 필드 */}
          <input type="file" ref={fileInputRef} />
          <button onClick={handleFileUpload}>Upload File</button>
        </div>
      );
    }
    
    export default FileInput;
    ```
    

## 제어 및 비제어 컴포넌트의 사용 상황 비교

상황 | SSOT 구현 방식 | 제어 컴포넌트 | 비제어 컴포넌트
-- | -- | -- | --
단일 필드 관리 | React 상태 | 상태에 따라 유효성 검사, 즉각적인 반영이 필요할 때 | 단순히 입력 값을 읽어와야 할 때
다중 필드 폼 | 복잡성에 따라 선택적 적용 | 동적 유효성 검사가 필요한 경우 | 필드 수가 많고, 단순히 제출 시 처리하는 경우
외부 데이터와의 동기화 | 상태와 동기화 | 외부 상태와 실시간으로 동기화되어야 하는 경우 | 초기값이 주어지고, 변경이 자주 발생하지 않을 때
성능 최적화가 중요한 경우 | 비제어 컴포넌트 사용 고려 | 리렌더링이 필요할 때만 상태 변경 | 성능 최적화가 필요한 경우

**Comment by gwangminjun** [comment]
## SSOT
Single Source Of Truth
애플리케이션에서  데이터를 하나의 장소(출처)에서만 관리하고, 모든 컴포넌트나 시스템이 이 데이터를 참조하도록 하는 원칙

## 제어 컴포넌트
- React에 상태(state)의해 값이 제어되는 입력 폼 엘리먼트
- React에서는 변경할 수 있는 state가 일반적으로 컴포넌트의 state 속성에 유지되며 useState에 의해 업데이트

```ts
function ControlledInput() {
  const [value, setValue] = useState("");  // 상태로 관리

  const handleChange = (event) => {
    setValue(event.target.value);  // 상태를 업데이트
  };

  return (
    <input type="text" value={value} onChange={handleChange} />
  );
}
```

## 비제어 컴포넌트
- React에서 DOM 요소가 자체적으로 상태를 관리하는 방식
- 값이 DOM의 내부 상태로 관리되며, React는 이 상태를 직접적으로 제어하지 않는다.
```ts
function UncontrolledInput() {
  const inputRef = useRef(null);  // DOM에 직접 접근

  const handleSubmit = () => {
    alert(`입력된 값: ${inputRef.current.value}`);
  };

  return (
    <div>
      <input type="text" ref={inputRef} />
      <button onClick={handleSubmit}>Submit</button>
    </div>
  );
}
```

## 상황에 따른 선택
- 사용자 입력과 같이 동적으로 변하는 데이터: 제어 컴포넌트 사용
- 파일 업로드, 비디오 플레이어 등 DOM 요소 자체의 상태가 중요한 경우: 비제어 컴포넌트 + ref 활용

**Comment by hyeonseong2023** [comment]
수고하셨습니당~
