### ISSUE TITLE
 11.1.2. 현재 정착된 CSS-in-JS 활용 트렌드에 대해 한 가지씩 설명해 주세요.

### ISSUE THREAD

**Issue by db-jay** [Gwangju-Web-Study/WoowahanTS_Study#44]
📝 p331 - 332

❓메타의 엔지니어 크리스토퍼 쉬도는 규모가 크고 동적인 웹앱을 유지보수하기 위해 해결해야할 CSS의 문제점을 설명하면서 해결책으로 CSS-in-JS 개념을 제시했습니다. 
다양한 환경과 스타일 요구 사항에 맞게 현 시점에도 발전하고 있는 CSS-in-JS 활용 트렌드에 대해 한 가지씩 설명해 주세요.

**Comment by gwangminjun** [comment]
## CSS-in-JS 활용 트렌드

### 주요 트렌드

- 서버 사이드 렌더링(SSR) 지원: 
Styled Components, Emotion 등에서는 SSR을 위한 API를 제공하여 서버에서 스타일을 미리 생성할 수 있습니다.


```ts
import { ServerStyleSheet } from 'styled-components';

const sheet = new ServerStyleSheet();

function handleRequest(req, res) {

 // 컴포넌트 렌더링
 // ReactDOMServer.renderToString : React 애플리케이션의 컴포넌트를 서버 측에서 렌더링하고 HTML 문자열을 반환하는 기능
 // sheet.collectStyles : 서버 측 렌더링 시 React 컴포넌트의 스타일을 수집하는 역할
  const html = ReactDOMServer.renderToString(sheet.collectStyles(<App />));
  
  // 스타일 정보 추출
 // sheet.getStyleTags : 서버 측 렌더링 시 수집된 스타일 정보를 HTML 스타일 태그 형태로 반환
  const styleTags = sheet.getStyleTags();
  
  // 클라이언트에 HTML과 스타일 태그 전달
  res.send(`
    <!DOCTYPE html>
    <html>
      <head>
      //반환된 스타일 태그 삽입
        ${styleTags}
      </head>
      <body>
        <div id="root">${html}</div>
      </body>
    </html>
  `);
}
```

**Comment by db-jay** [comment]
## **Next.js에서 CSS-in-JS를 활용한 최적화 장점**

- **SSR 지원**
    - CSS-in-JS는 Next.js의 SSR 환경과 결합해 브라우저가 필요한 스타일만 로드하므로 초기 렌더링 속도를 향상시킴.
    - 사용자에게 스타일이 완전히 적용된 페이지를 제공함.
- **Theming과 상태 관리 통합**
    - 전역 테마 관리와 상태 기반 동적 스타일링(예: 다크 모드)구현 가능.
        
        ```tsx
        import { ThemeProvider } from "styled-components";
        
        function App({ Component, pageProps }) {
          const [isDarkMode, setIsDarkMode] = useState(false);
        
          return (
            <ThemeProvider theme={isDarkMode ? darkTheme : lightTheme}>
              <button onClick={() => setIsDarkMode(!isDarkMode)}>
                Toggle Theme
              </button>
              <Component {...pageProps} />
            </ThemeProvider>
          );
        }
        
        export default App;
        
        ```
        
- **번들 크기 최소화**
    - Next.js의 코드 분할과 Tree Shaking을 활용해 필요하지 않은 스타일이 제거됨.

**Comment by hyeonseong2023** [comment]
# StyleX
![image](https://github.com/user-attachments/assets/07032b94-cee2-4711-8c88-76728382447f)
* 2023년 12월 Meta에서 개발한 오픈 소스 CSS-in-JS 라이브러리
* 페이스북, 인스타그램, 쓰레드 등의 앱을 구동하고 있는 스타일링 시스템

## 기존 CSS-in-JS와의 차별점
|         | CSS-in-JS | StyleX |
|------|-----------|---------|
| 처리 시점 | **런타임**에 스타일을 **동적**으로 생성 | **빌드 시점**에 **정적** CSS 생성 |
| 성능 특성 | 런타임 오버헤드 존재 | 컴파일 타임 처리로 런타임 오버헤드 최소화 |
| 구현 방식 | JavaScript 내에서 동적으로 스타일 처리 | 정적 스타일 추출 및 최적화 |
---
### => 기존 CSS-in-JSS의 런타임 및 성능 문제를 해결하기 위해 탄생

## 예시 코드
### 컴파일 전
```jsx
import * as stylex from 'stylex';
const styles = stylex.create({
  red: {color: 'red'},
});
let a = stylex.props(styles.red);
```
### 컴파일 후
```js
// js
let a = {className: 'x1e2nbdu'};
```
```css
// css
.x1e2nbdu { color: red; }
```
### 사용 예시
```jsx
<div {...stylex.props(styles.red)} />
```
