### ISSUE TITLE
12.4. 모노레포 도구별 특징을 비교하여 설명해주세요.

### ISSUE THREAD

**Issue by db-jay** [Gwangju-Web-Study/WoowahanTS_Study#45]
📝 356 - 361

❓ 모노레포를 사용하는 경우, 여러 프로젝트가 공통으로 사용하는 유틸리티 라이브러리를 효과적으로 관리하려면 어떤 방법을 사용해야 할까요? 모노레포 도구별 특징을 비교하여 설명해주세요.

**Comment by db-jay** [comment]
## 모노레포 도구별 비교
- **Lerna**:
    - https://lerna.js.org/
    - 기존 워크플로와 쉽게 통합할 수 있는 간단한 패키지 관리가 필요할 때.
    - 독립적인 패키지 버전 관리를 선호할 때.
- **Nx**:
    - https://nx.dev/
    - 빌드, 테스트, 배포를 포함한 전체 워크플로를 모노레포에서 관리해야 할 때.
    - 대규모 프로젝트에서 의존성을 효율적으로 관리하려 할 때.
- **Turborepo**:
    - https://turbo.build/
    - 빠른 빌드와 간단한 설정이 중요한 경우.
    - Next.js, Vercel 기반의 모노레포 프로젝트를 관리할 때.

**Comment by hyeonseong2023** [comment]
# pnpm workspaces
![image](https://github.com/user-attachments/assets/58abd7c4-5894-46b4-8740-4f216b2f7f8b)
---
# Yarn Workspaces
![image](https://github.com/user-attachments/assets/9b898703-0954-4eee-b2a8-c4b1a13f2422)
---
# 비교
| 특징 | pnpm workspace | yarn workspace |
|------|---------------|----------------|
| 디스크 공간 효율성 | 하드 링크 사용으로 전역 저장소에서 패키지를 공유 ⬆️ |  node_modules에 패키지를 물리적으로 복사하여 저장함으로서 중복 패키지 발생 ⬇️  |
| 의존성 관리 | 엄격한 관리로 유령 의존성 방지 | 호이스팅으로 인한 유령 의존성 가능성 존재 |
| 설정 파일 | `pnpm-workspace.yaml` | `package.json`의 workspaces 필드 |
| 성능 | 병렬 설치와 하드 링크로 빠른 속도 | 호이스팅 처리로 상대적으로 느림 |
| 부가 기능 | - workspace: 접두사로 내부 패키지를 쉽게 참조<br>- 내장 모노레포 지원<br>- --filter 플래그로 특정 패키지만 선택적으로 작업 | - 플러그인 시스템<br>- 대규모 커뮤니티 지원<br>- 검증된 안정성 |

💡유령 의존성(phantom dependency)
* 중복 라이브러리의 위치 때문에 발생하는 현상
* package.json에 명시하지 않은 라이브러리를 사용할 수 있는 것
---
:bulb:2023 모노레포 순위 https://2023.stateofjs.com/ko-KR/libraries/monorepo_tools/
:bulb:정리 사이 https://monorepo.tools/#what-is-a-monorepo

**Comment by gwangminjun** [comment]
# 대표적인 기업의 모노레포 예시

1. Bazel (Google)
- https://bazel.build/?hl=ko
- 프로젝트 간 의존성 관리와 빌드 프로세스를 자동화하는 데 강점
- 대규모 프로젝트에 적합하지만, 초기 설정이 복잡

2. Rush (Microsoft)
- https://rushjs.io/
- 프로젝트 간 공유 코드를 별도의 "Shared Projects"로 관리할 수 있어 재사용성이 높습니다.
- 복잡한 대규모 프로젝트에 적합하지만, 설정 및 학습 과정이 다소 복잡

3. Berry (Yarn)
- https://toss.tech/article/node-modules-and-yarn-berry
- 핵심 기능도 플러그인을 이용하여 개발되어 있을 만큼 플러그인 친화적인 환경
- 높은 완성도의 워크스페이스 기능을 제공합
