### ISSUE TITLE
12.3.3 타입스크립트 마이그레이션 주의점

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#47]
📝 356p

❓ 타입스크립트로 마이그레이션을 진행하는 과정에서 책에 나와있지 않은 단계 혹은 주의해야 할 점을 알려주세요

**Comment by hyeonseong2023** [comment]
## 점진적 마이그레이션 우선 순위
### 1. 독립적인 유틸리티 함수
* 의존성이 적은 순수 함수부터 진행
* 날짜 포맷팅, 문자열 처리 등
```ts
// Before
Date.prototype.getY = function () {
  var date = new Date();
  return '' + date.getFullYear();
};

// After
Date.prototype.getY = function(): string { 
  const date = new Date(); 
  return date.getFullYear().toString(); 
};
```

### 2. 자주 사용하는 데이터 구조 혹은 API 응답
```java
@Data
public class AjaxDataDTO {
	private boolean success = false;
	private String message;
	private Object data;
	private long total;
	private List<Object> list = new ArrayList<Object>();
}
```
```ts
interface AjaxResponse<T = any> {
  success: boolean;
  message?: string;
  data: T;
  total: number;
  list: T[];
}
```

**Comment by gwangminjun** [comment]
# 타입스크립트로 마이그레이션시 주의해야 할 점

## 주의점
1. 타입 정의 파일 관리: 외부 라이브러리에 대한 타입 정의 파일(*.d.ts)은 관리해야 합니다. 
- 외부 라이브러리인 Axios의 경우 최신 버전의 타입 정의 파일 @types/axios를 설치하여 사용해야 합니다.

2. 테스트 강화
- 회원 가입, 로그인, 게시글 CRUD 등의 핵심 기능에 대한 테스트 코드를 작성하여 마이그레이션 이후에도 기존 기능이 동작하는지 검증할 수 있습니다.

![image](https://github.com/user-attachments/assets/38f0bd0a-bfa4-4e1f-96e3-10f0217d3a21)
# jest
JavaScript 테스트 프레임워크

## typescript 에서 사용

```js
//jest.config 파일 작성
module.exports = {
  preset: 'ts-jest',  //TypeScript 지원을 위한 preset 설정
  testEnvironment: 'node', //Node.js 환경에서 테스트 실행
};
```

```ts
//test 파일 작성
function sum(a: number, b: number): number {
  return a + b;
}

test('adds 1 + 2 to equal 3', () => {
  expect(sum(1, 2)).toBe(3);
});
```

```shell
npx jest // 테스트
```

**Comment by db-jay** [comment]
## **tsconfig 설정 최적화**

- 타입스크립트 설정 파일(`tsconfig.json`)은 마이그레이션의 핵심!
- 설정을 너무 엄격하게 시작하면 초기에 많은 에러가 발생할 수 있으니 주의!
    
    ```json
    // 초기 설정 예
    {
      "compilerOptions": {
        "target": "ES6",
        "module": "CommonJS",
        "strict": false, // 점진적 마이그레이션에서는 비활성화
        "allowJs": true,
        "checkJs": false,
        "outDir": "./dist",
        "rootDir": "./src",
        "noEmit": true},
      "include": ["src/**/*"],
      "exclude": ["node_modules"]
    }
    ```
    
    ### ⚠️ 추가 주의
    
    1. **`strict` 모드**:
        - 마이그레이션 완료 후 활성화하여 타입 안정성을 확보해야함.
        - 초기에는 비활성화하고 파일별로 점진적으로 활성화(`// @ts-check`)하는 방법을 권장함.
    2. **`esModuleInterop`**:
        - CommonJS와 ES 모듈의 상호 호환성을 처리할 때 활성화

## **레거시 코드 호환**

- **레거시 API 사용**:
    - 타입스크립트에서 사용하기 어려운 레거시 API는 별도의 어댑터를 작성하거나 타입 선언 활용.
    
    ```tsx
    typescript
    코드 복사
    function legacyApi(data: any): any {
      // 레거시 코드
    }
    
    const typedApi = (data: string): string => {
      return legacyApi(data);
    };
    ```
    
- **점진적 도입**:
    - 레거시 코드는 `@ts-ignore`를 사용해 일시적으로 타입 검사를 무시하고 점직적으로 변환
    
    ```tsx
    typescript
    코드 복사
    // @ts-ignore
    const result = legacyApi("test");
    
    ```
