### ISSUE TITLE
10. useContext와 상태 관리 라이브러리의 차이

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#48]
📝 306p

❓ React의 대표적인 훅 중 하나인 useContext는 컴포넌트 트리 전체에 데이터를 전달할 수 있는 방법입니다. 공식 사이트에서는 이를 통해 어느 컴포넌트에서나 데이터에 접근할 수 있다고 설명하고 있는데요, 이는 상태 관리 라이브러리와 비슷해 보이는 기능입니다. useContext와 상태 관리 라이브러리의 차이점에 대해 설명해주세요!

**Comment by hyeonseong2023** [comment]
## useContext
* Context Api에서 제공된 데이터를 손쉽게 읽어올 수 있도록 도와주는 hook

### 사용 방법
```jsx
// App.js
import { createContext, useContext } from 'react';

// 테마 정보 저장 (여기서는 dark)
const ThemeContext = createContext(null);

// 최상위 컴포넌트
export default function MyApp() {
  return (
    // Provider : 하위 컴포넌트에 value 값 전달
    <ThemeContext.Provider value="dark">
      <Form />
    </ThemeContext.Provider>
  )
}

function Form() {
  return (
    <Panel title="Welcome">
      <Button>Sign up</Button>
      <Button>Log in</Button>
    </Panel>
  );
}

function Panel({ title, children }) {
  // 저장한 Context 테마 값 가져오기
  const theme = useContext(ThemeContext);
  const className = 'panel-' + theme;
  return (
    <section className={className}>
      <h1>{title}</h1>
      {children}
    </section>
  )
}

function Button({ children }) {
  const theme = useContext(ThemeContext);
  const className = 'button-' + theme;
  return (
    <button className={className}>
      {children}
    </button>
  );
}
```
![image](https://github.com/user-attachments/assets/7212984d-1fd9-41fb-bc58-c7cb8a27abd8)
![image](https://github.com/user-attachments/assets/b2762eb3-bdd9-452c-b521-09969ba05d7c)

💡출처: https://ko.react.dev/reference/react/useContext

---
## VS 🥊
| 구분 | useContext | 상태관리 라이브러리 |
|------|------------|----------------------------------|
| 규모 | - 소규모 애플리케이션<br>- 상태 업데이트가 빈번하지 않은 경우 | - 대규모 애플리케이션<br>- 복잡한 상태 로직이 필요한 경우 |
| 용도 | - 전역 설정값 관리 (테마, 언어 등) | - 복잡한 상태 로직 처리<br>- 서버 상태 관리<br>- 상태 변화 추적 (디버깅) |
| 장점 | - React 내장 기능으로 별도 설치 불필요<br>- 번들 크기에 영향 없음 | - 체계적인 상태 관리 가능<br>- 성능 최적화 기능 제공<br>- 대규모 팀 협업에 용이 |
| 단점 | - 복잡한 상태 업데이트 처리 어려움<br>- 디버깅 도구 부족 | - 초기 설정과 보일러플레이트 코드 필요<br>- 번들 크기 증가 |
| 러닝커브 | - React 기본 개념만 알면 사용 가능<br>- 상태관리 입문용으로 적합 | - 라이브러리별 특성 학습 필요<br>- 미들웨어 등 추가 개념 학습 필요 |

**Comment by gwangminjun** [comment]
React의 `useContext`와 상태 관리 라이브러리의 주요 차이:

| 구분 | `useContext` | 상태 관리 라이브러리 |
|------|-------------|----------------------|
| 범위 | 컴포넌트 트리 내 전역 상태 | 전체 애플리케이션의 상태 |
| 상태 관리 복잡성 | 간단한 상태 관리 | 복잡한 상태 관리 |
| 재랜더링 시점 | 컨텍스트 변경 시 | 특정 상태 변경  |
| 재랜더링 객체 | 해당 컨텍스트를 구독하는 모든 컴포넌트 | 선택적 재랜더링|
| 개발 도구 지원 | 제한적 | 다양한 개발 도구 연동 지원 |

요약하면, `useContext`는 간단한 상태 관리에, 상태 관리 라이브러리는 복잡한 상태 관리에 더 적합합니다.

++
컴포넌트 트리: React 애플리케이션의 계층 구조
전체 애플리케이션: 컴포넌트 트리를 포함하는 더 큰 단위로, 전역 상태, 라우팅, 서비스 등을 관리

**Comment by db-jay** [comment]
## useContext

- **간단한 데이터 전달**:
    - 주로 **전역 데이터**(예: 현재 사용자, 테마, 언어 설정 등)를 쉽게 공유하기 위해 사용.
    - React Context API와 함께 사용되며, 상태를 저장하는 기능 자체는 없음.
- **상태 관리 기능 없음**:
    - 상태를 유지하거나 업데이트하는 기능은 없으며, 
    상태는 별도의 `useState` 또는 `useReducer` 훅과 결합하여 관리.
- **리렌더링**:
    - Context의 값이 변경되면 **모든 구독 중인 컴포넌트**가 리렌더링됨.
    - Context를 대규모 상태 관리에 사용하는 데 성능 문제가 될 수 있음.
- **간단한 전역 상태 관리에 적합**
    - 프로젝트의 복잡성이 증가하면 Context와 `useReducer`를 조합해야 하므로 코드가 복잡해질 수 있음.
