### ISSUE TITLE
1.2.3_PropTypes 과 TypeScript 의 차이와 TypeScript를 사용해야하는 이유는 무엇일까요?

### ISSUE THREAD

**Issue by BaekWeb** [Gwangju-Web-Study/WoowahanTS_Study#5]
📝 p28

❓ PropTypes 과 TypeScript 의 차이와 TypeScript를 사용해야하는 이유는 무엇일까요?

**Comment by hyeonseong2023** [comment]
PropTypes는 리액트에서만 사용 가능하며, 그마저도 컴포넌트 간의 데이터 전송 수단인 props에서만 타입을 체크합니다.
그에 반해 TypeScript는 리액트에만 국한되지 않고 JavaScript를 사용하는 곳에 도입이 가능하며 모든 타입을 검사합니다.

이러한 TypeScript는 컴파일 단계에서 검사하기에 런타임 에러를 사전에 방지해주어 안정성이 올라가며, 타입 자동 완성 기능으로 개발 생산성이 향상되는 장점이 있습니다.

**Comment by Clt689** [comment]
## PropTypes 과 TypeScript 의 차이
### 1. 런타임 및 컴파일 시간 유형 확인
PropTypes는 애플리케이션이 브라우저에서 실행되는 동안 런타임 중에 유형 검사를 수행
그러나 TypeScript는 TypeScript 코드가 JavaScript로 컴파일될 때 컴파일 시간 동안 유형 검사를 수행

### 2. 구문 및 의미 강조
두 도구 모두 컴포넌트의 props에 대한 정보와 함께 자동 완성 기능을 제공하는 플러그인이 있다. 그러나 TypeScript의 강조 표시 도구는 PropTypes를 능가한다고 함

### 3. TypeScript의 고급 기능
PropTypes가 제공할 수 없는 TypeScript의 props 유형을 지정할 수 있는 방법은 속성 A가 true인 경우 속성 C도 제공해야 한다는 조건부 유형 검사를 수행 가능

---
## TypeScript의 장점(사용해야하는 이유)
- 안정성 보장
- 개발 생산성의 향상
- 협업에 유리
- JS에 점진적으로 적용 가능

<br>

출처 : https://velog.io/@serenity/React-TypeScript-vs-PropTypes

**Comment by gwangminjun** [comment]
# PropTypes 과 TypeScript 의 차이

## PropTypes
React의 props에 대한 "런타임 유형 검사 도구"
컴포넌트에서 예상되는 props 유형을 정의

### PropTypes의 오류
PropTypes는 프로덕션 응용 프로그램(vscode)에서 경고를 따로 제공하지 않으며 경고는 "개발 중에만" 표시

개발자 모드에서 직접 실행해보기 전(npm start)까지는 코드를 작성하면서는 해당 오류를 바로 캐치할 수 없음

## TypeScript
React와 함께 TypeScript를 사용하면 컴파일할 때 확인할 내용을 props에 추가할 수 있다.

### TypeScript의 오류
예기치 않은 props를 전달할 때 vscode(IDE)에 즉각적인 IntelliSense 경고가 표시
코드를 작성하는 순간순간 오류를 바로 캐치

TypeScript를 사용하면 다음과 같이 props 요구 사항을 위반할 시 npm run build를 실행할 수 없다.

## TypeScript와 PropTypes 비교
### 런타임 및 컴파일 시간 유형 확인
- PropTypes : 브라우저에서 실행되는 동안 런타임 중에 유형 검사를 수행
- TypeScript : 컴파일될 때 컴파일 시간 동안 유형 검사를 수행
### 구문 및 의미 강조
- TypeScript의 강조 표시 도구는 PropTypes를 능가한다 (IDE 제공)
- TypeScript는 예상되는 props의 데이터 유형이 제공되지 않을 때 구성 요소를 적절하게 강조 표시하고 솔루션에 대한 통찰력을 제공
## TypeScript의 고급 기능
### 조건부 유형 검사
       - 속성 A가 true인 경우 속성 C도 제공해야 한다
       - type Props =
    | {
            type: "error";
            message: "";
      }
    | {
            type: "success";
      };
  

참조 
- https://velog.io/@serenity/React-TypeScript-vs-PropTypes

**Comment by BaekWeb** [comment]
PropTypes 과 TypeScript 의 차이
1. 타입 검사 시점이 다름
PropTypes의 경우 런타임(코드가 실제로 실행 될때) 타입을 검사
TypeScript의 경우 컴파일 타임(코드 작성후 컴파일 하는 동안) 타입 오류를 검사

2. JavaScript 요소에 대한 타입 검사여부
PropTypes의 경우 자바스크립트는 타입검사를 하지않고
TypeScript는 자바스크립트 요소에 타입검사를 수행함

3. 타입의 강제성과 에러처리
PropTypes의 경우 타입이 잘못되도 에러를 발생시키지 않고 경고로 로그를 남김 
즉, 경고만하고 코드 동작을 막거나 빌드를 실패하게 하지 않음

TypeScript 사용 이유는?
PropTypes은 작은 프로젝트를 빠르게 적용하기 위해 사용하는 것이 좋습니다.
TypeScript의 경우 중대형 프로젝트 위주로 코드의 일관성을 통해 유지보수와 확장성을 증가시키고
코드의 일관성을 갖추기 때문입니다.

PropTypes이 중대형 프로젝트에 어울리지 않는 이유는?
1. 복잡한 타입 관리**
 - 인터페이스(interface), 제네릭(Generics)
2. 정적 타입 검사** 
- TypeScript는 컴파일 타임으로 코드를 실행 하기전에 타입 오류 미리 확인 가능한데
   PropTypes 은 런타임 타입검사로 실행을 해야 확인가능
   
   
   ```js
   
   interface Address {
  street: string;
  city: string;
  postalCode: string;
  country: string;
}  
   ```
   
   ```js
   
interface User {
  id: number;                     ## 고유 ID
  name: string;                   ## 사용자 이름
  age: number;                    ## 나이
  email: string;                  ## 이메일 주소
  isActive: boolean;              ## 활성화 여부
  phoneNumber?: string;           ## 선택적 속성: 전화번호
  address?: Address;              ## 선택적 속성: 주소
  roles: string[];                ## 사용자 역할 (예: ["admin", "user"])
  createdAt: Date;                ## 계정 생성일
  lastLogin?: Date;               ## 선택적 속성: 마지막 로그인 날짜
}
```
