### ISSUE TITLE
9.1.2 useEffect를 라이프사이클 측면에서 설명해주세요

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#51]
📝 p290

❓ (1)리액트에서 라이프사이클의 기본적인 개념과, 
(2)useEffect의 흐름을 라이프사이클 측면에서 설명해주세요.

**Comment by gwangminjun** [comment]
# React 라이프사이클

1. 마운팅(Mounting) - 컴포넌트가 처음 DOM에 생성되고 렌더링되는 단계
  - constructor() - 컴포넌트가 처음 생성될 때 호출
  - render() - 컴포넌트의 UI를 렌더링
  - componentDidMount() - 컴포넌트가 DOM에 마운트된 직후 호출

2. 업데이팅(Updating) - 컴포넌트의 props나 state가 변경되어 재렌더링되는 단계
  - shouldComponentUpdate() - 컴포넌트 업데이트 여부를 결정
  - render() - 변경된 내용을 다시 렌더링
  - componentDidUpdate() - 업데이트가 완료된 후 호출

3. 언마운팅(Unmounting) - 컴포넌트가 DOM에서 제거되는 단계
  - componentWillUnmount() - 컴포넌트가 제거되기 직전에 호출

# useEffect와 라이프사이클
  - useEffect는 함수형 컴포넌트에서 라이프사이클 메서드를 대체하는 Hook
```ts
//1. componentDidMount 대체
useEffect(() => {
  // 마운트 시 한 번만 실행
}, [])

//2. componentDidUpdate 대체
useEffect(() => {
  // 의존성 배열의 값이 변경될 때마다 실행
}, [someValue])
```

**Comment by db-jay** [comment]
## React의 라이프 사이클

- 리액트 컴포넌트는 **생성 → 업데이트 → 제거**의 라이프사이클을 따른다.

라이프사이클 | 컴포넌트 동작 | useEffect 동작
-- | -- | --
마운트 | 함수형 컴포넌트가 호출되며 렌더링됩니다. | useEffect는 기본적으로 호출되며, 빈 의존성 배열 []을 사용해 한 번만 실행됩니다.
업데이트 | 상태(state)나 속성(props)이 변경되면 컴포넌트가 다시 호출됩니다. | 의존성 배열 [dependency]에 추가된 값이 변경될 때만 실행됩니다.
언마운트 | 컴포넌트가 DOM에서 제거되며 더 이상 호출되지 않습니다. | useEffect의 클린업 함수가 실행됩니다.


## useEffect의 라이프사이클

### 1. 마운트

- 첫 렌더링
- 렌더링 완료 후 Effect 실행

### 2. 업데이트

- props/state 변경
- 리렌더링 발생
- 이전 Effect의 클린업 함수 실행
- 새로운 Effect 실행

### 3. 언마운트

- 최종 클린업 함수 실행
- 컴포넌트 제거

![image](https://github.com/user-attachments/assets/2ba7a3a2-99f4-4181-bfaa-cb497bb5d7ea)

``` ts
function UserProfile({ userId }: { userId: string }) {
    const [data, setData] = useState(null);

    useEffect(() => {
        // 1. 마운트 시 실행
        console.log("컴포넌트 마운트됨");

        // 2. 데이터 가져오기
        const fetchData = async () => {
            const response = await fetch(`/api/user/${userId}`);
            const userData = await response.json();
            setData(userData);
        };

        fetchData();

        // 3. 클린업 함수
        return () => {
            console.log("정리 작업 수행");
            // 데이터 구독 해제, 타이머 정리 등
        };
    }, [userId]); // userId가 변경될 때마다 실행

    return (
        <div>
            {data ? (
                <h1>{data.name}의 프로필</h1>
            ) : (
                <p>로딩 중...</p>
            )}
        </div>
	    );
}
```

**Comment by hyeonseong2023** [comment]
# 라이프사이클
## 개념
* 리액트 컴포넌트의 생성(mount), 업데이트(update), 제거(unmount) 단계에서 자동으로 호출되는 메서드들의 실행 순서
## 단계별 특징
### 1. 마운트
* 컴포넌트가 페이지에 새로 추가될 때 발생하는 단계
### 2. 업데이트
* 다음의 경우 업데이트
  * props의 변경
  * state의 변경
  * 부모 컴포넌트 리렌더링
### 3. 언마운트
* 컴포넌트가 DOM에서 제거될 때 발생하는 단계

# useEffect
### 1. 마운트
```ts
useEffect(() => {
  console.log("마운트 시점 발생")
}, [])
```
### 2. 업데이트
```ts
const [count, setCount] = useState(0);

// 1. 첫 렌더링 때 실행되고 그 후부터는 count의 값이 변할 때마다 실행  
useEffect(() => {
  console.log("업데이트 시점 발생")
}, [count])

// 2. 2번째 인자 배열(deps)을 생략하게 되면 컴포넌트가 렌더링이 될 때마다 계속 코드가 실행
useEffect(() => {
  console.log("업데이트 시점 발생")
})
```
### 3. 언마운트
```ts
useEffect(() => {
  return () => {
    console.log("언마운트 시점 발생")
  }
}, [])
```
