### ISSUE TITLE
2.2.8 enum 타입의 특징과 사용방법은 무엇이고 enum 타입을 트리쉐이킹 할 수 있는 방법은 무엇인가요?

### ISSUE THREAD

**Issue by gwangminjun** [Gwangju-Web-Study/WoowahanTS_Study#6]
📝 57p

❓ 질문
enum 타입의 특징과 사용방법은 무엇이고 enum 타입을 트리쉐이킹 할 수 있는 방법은 무엇인가요?

**Comment by Clt689** [comment]
# enum
## 특징
- 열거형을 정의할 수 있음
  - 주로 상수 집합을 표현하는데 유용
- 런타임에 객체로 변환됨
- 런타임에 실제 객체로 존재하고, 함수로 표현 가능
## 사용 방법

```ts
enum Direction {
    Up = 1,   // 1
    Down,     // 2
    Left,     // 3
    Right     // 4
}
```
- 숫자 열거형에서 첫 번째 값을 지정하면, 그다음 값들은 순차적으로 증가

## enum 타입을 트리쉐이킹하는 방법
### 1. `const enum` 사용
: 컴파일 타임 상수처럼 작동하며, 인라인 방식으로 코드를 최적화하여 트리쉐이킹을 가능하게 한다.
- 사용되지 않는 const enum 값은 최종 번들에서 제거됨.
### 2. 리터럴 타입 사용
: 유니언 타입 등을 사용해 더 가볍고 트리쉐이킹이 용이한 코드를 작성할 수 있다.

**Comment by db-jay** [comment]
### enum 타입 특징

1. 런타임에서 변환되는 값.
2. 관련된 상수들의 집합을 정의할 때 사용.

### enum 타입 주요 사용법

1. 숫자 또는 문자열 값 사용.
2. 기본적으로 0부터 시작하는 숫자 값을 자동으로 할당.
3. 명시적으로 값 지정 가능.
4. 역방향 매핑(값으로 이름 접근) 가능.
    
    ```tsx
    enum Direction {
    	Up,
    	Down,
    	Left,
    	Right
    }
    
    console.log(Direction.Up);    // 출력: 0
    console.log(Direction[2]);    // 출력: "Left"
    ```
    

### enum 타입 트리쉐이킹 방법

`const enum` 을 사용하면 `enum` 정의 자체가 완전히 제거되고, 사용된 값만 대체되므로 트리쉐이킹 가능.

1. 컴파일 시점 최적화 :
`const enum`은 TypeScript 컴파일러에 의해 컴파일 시점에 완전히 제거되며, `enum` 멤버를 사용하는 곳에 값이 직접 인라인으로 대체됨.
2. 런타임 객체 생성 방지 :
런타임에 객체를 생성하지 않으므로 번들크기를 줄일 수 있음.
3. 사용 제한 :
일반 `enum` 에 비해 사용할 수 있는 기능이 제한적임.  (ex. 역방향 매핑 불가)
    
    ```tsx
    // 1. cosnt enum 사용
    const enum Color {
      Red = "#FF0000",
      Green = "#00FF00",
      Blue = "#0000FF"
    }
    
    let favoriteColor = Color.Blue;
    
    // 2. 컴파일 결과
    let favoriteColor = "#0000FF";
    ```

**Comment by hyeonseong2023** [comment]
### enum 타입의 특징 및 사용 방법
enum(enumeration) 타입이란 TypeScript에서 지원하는 기능 중 하나로, 이름이 있는 상수들의 집합을 정의할 때 사용합니다.

```js
// 선언
enum Direction {
  Up = 1,
  Down,
  Left,
  Right,
}

// 사용 방식
console.log(Direction.Down); // 2
console.log(Direction[2]); // Down
```
특징으로 숫자 값을 초기화하지 않아도 배열 인덱스처럼 1씩 추가되어 초기화되며, 
아무것도 초기화하지 않을 경우에는 초기값이 0부터 시작됩니다.
이러한 인덱스 번호와 같은 기능으로 역매핑이 가능합니다.

### enum 타입을 트리쉐이킹 할 수 있는 방법
enum 타입은 컴파일 과정에서 즉시실행함수(IIFE) 코드로 바뀌며 트리쉐이킹이 되지 않는 문제가 있습니다.
const enum을 사용하면 컴파일 과정에서 인라인(컴파일러나 번들러가 코드를 변환하는 과정에서 특정 코드의 참조를 해당 참조의 실제 값으로 직접 대체) 처리됩니다.
위 코드의 예시로 따르면 Direction 객체는 생성되지 않고 console.log(1); 로 변환되며 트리쉐이킹이 이루어집니다.

그러나 단점으로는 일반 상수(const)는 대체로 컴파일 과정에서 트리쉐이킹 되며, 
때문에 런타임 이후 enum 객체를 직접적으로 참조할 때 문제가 발생할 수 있습니다.

**Comment by gwangminjun** [comment]
## Enum
- 특정 값(상수)들의 집합
- 특정 값을 고정하는 또다른 독립된 자료형

### 인덱싱
- 기본적으로 enum은 0부터 시작하여 멤버들의 번호를 매긴다
```ts
enum Week {
  Sun, // 0
  Mon, // 1
  Tue, // 2
  Wed, // 3
  Thu, // 4
  Fri, // 5
  Sat  // 6
}
```

### 상수
enum을 사용하면 컴파일 후에도 객체가 남는다

해당 특징 때문에 번들 파일이 불필요하게 커질수 있다는 단점이 있다.

```ts
enum Bool {
  True,
  False,
  FileNotFound
}
let value = Bool.FileNotFound;

//컴파일

var Bool;
(function (Bool) {
  Bool[(Bool["True"] = 0)] = "True";
  Bool[(Bool["False"] = 1)] = "False";
  Bool[(Bool["FileNotFound"] = 2)] = "FileNotFound";
})(Bool || (Bool = {}));
let value = Bool.FileNotFound;
```

const Enum을 사용
```ts
const enum Bool {
  True,
  False,
  FileNotFound
}
let value = Bool.FileNotFound;

//컴파일

let value = 2; /* FileNotFound */
```

### reverse mapping
객체에서 키와 값의 위치를 바꿔서 새로운 객체를 생성

숫자형 enum 에서만 사용가능
```ts
enum Enum {
  A
}
let a = Enum.A; // 키로 값을 획득 하기
let keyName = Enum[a]; // 값으로 키를 획득 하기
```

## 트리쉐이킹
트리 쉐이킹은 사용하지 않는 코드를 제거하는 방식

Tree-shaking을 통해서 빌드 시스템을 구성하면 export 했지만 아무데서도 import 하지 않은 모듈이나 사용하지 않는 코드를 삭제해서 번들 크기를 줄여서 렌더링 시간을 줄일 수 있다.

### enum 트리쉐이킹
#### enum이 트리쉐이킹 되지 않는 이유
Typescirpt  컴파일러는 이를 IIFE(즉시실행 함수)로 구현을 해냈다.  <br>
Rollup과 같은 번들러는 IIFE를 사용하지 않는 코드라고 판단할 수 없어서 <br>
Tree-shaking이 되지 않는다. 


#### enum의 트리쉐이킹 시도

const enum 사용
```ts
const enum MOBILE_OS {
    IOS = 'iOS',
    ANDROID = 'Android',
}
const ios = MOBILE_OS.IOS

// 트랜스 파일

const ios = "iOS" /* IOS */;
```

Tree-shaking이라는 관점에서는 Union Types와 같습니다. <br>
사용하지 않는다면 번들에 포함되지 않습니다. <br>
하지만 긴 문자열을 할당하는 경우에는 Union types와 비교해 다소 불리한 점이 있다 <br>

```ts
// TypeScript
const enum NAME {
  JUGEM = '寿限無寿限無五劫の擦り切れ海砂利水魚の…', // 일본에서 '김수한무 거북이와 두루미 삼천갑자 동방삭...'과 비슷한 용도로 사용하는 긴 이름입니다.
TARO = '다로', 
JIRO = '지로', 
} 
const isJugem = name === NAME.JUGEM
 
// JavaScript 트랜스파일 후
const isJugem = name === "u5BFFu9650u7121u5BFFu9650u7121u4E94u52ABu306Eu64E6u308Au5207u308Cu6D77u7802u5229u6C34u9B5Au306Eu2026" /* JUGEM */;
```


const enum은 TypeScript가 트랜스파일(transpile)할 때 컴파일 타임에 값으로 치환하는 방식으로 작동 <br>
즉, 런타임에 const enum이 실제로 존재하는 것이 아니라, 그 값을 코드 내에서 직접 사용하는 방식으로 변환

NAME.JUGEM을 사용하면, 컴파일된 자바스크립트에서는 NAME.JUGEM 대신 이 긴 문자열이 그대로 들어가게 됩니다

const enum의 트리쉐이킹 최적화 저해
1. 상수 치환: 트랜스파일 후 이 긴 문자열은 코드 여러 곳에 직접 치환됩니다. 이 과정에서 문자열 상수가 여러 곳에 복사되어 들어가게 됩니다.
2. 사용된 문자열 유지: 트리 쉐이킹은 사용되지 않는 코드를 제거하는 것이 목표인데, 
이 긴 문자열이 여러 곳에서 사용된다고 판단되면 트리 쉐이킹이 해당 문자열을 제거하지 못합니다.
3. 번들 크기 증가: 긴 문자열이 여러 군데에서 사용될수록, 최종 번들 파일 크기가 증가합니다. 특히 이 경우, 매우 긴 문자열이 코드에 여러 번 복사되면 파일 크기에 부정적인 영향을 미치게 됩니다.




### reference
- https://inpa.tistory.com/entry/TS-%F0%9F%93%98-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-enum-%EC%A0%95%EB%A6%AC
- https://joshua1988.github.io/ts/guide/enums.html#%EB%A6%AC%EB%B2%84%EC%8A%A4-%EB%A7%A4%ED%95%91-reverse-mapping
- https://velog.io/@hhhminme/%EB%84%A4-Enum-%EB%88%84%EA%B0%80-Typescript%EC%97%90%EC%84%9C-Enum%EC%9D%84-%EC%93%B0%EB%83%90
- https://engineering.linecorp.com/ko/blog/typescript-enum-tree-shaking

**Comment by BaekWeb** [comment]
enum 타입의 특징과 사용방법은 무엇이고 enum 타입을 트리쉐이킹 할 수 있는 방법은 무엇인가요?

enum 타입의 특징 
1. 런타임에서 객체로 변환되어 자바스크립트의 값으로 사용


enum 사용 방법
1. 숫자 or 문자열 열거형 사용
2. 0부터 시작하는 숫자 값을 자동으로 할당 (인덱싱)
3. 양방향 매핑 - 값과 키를 통해 접근 가능하다.
```
enum Direction {
  Up = 1,
  Down,
  Left,
  Right
}

let dir = Direction.Up;  // dir은 1입니다.
let dirName = Direction[1];  // dirName은 "Up"입니다.
```

enum 트리쉐이킹 방법
- const enum 사용
 -> 일반 enum은 객체의 값과 이름을 저장하는 반면 const enum은 값을 직접 코드에 삽입

**Comment by db-jay** [comment]
https://github.com/Gwangju-Web-Study/WoowahanTS_Study/issues/6#issuecomment-2295045135

타입스크립트에서 enum의 reverse mapping은 숫자형 enum에서만 자동으로 생성됩니다. 이는 타입스크립트의 enum 구현 방식 때문입니다.

이러한 차이는 타입스크립트가 enum을 컴파일할 때 생성하는 JavaScript 코드의 차이에서 비롯됩니다. 숫자형 enum은 역방향 조회를 위한 추가적인 객체를 생성하지만, 문자열 enum은 그렇지 않습니다.
따라서, 타입스크립트에서 reverse mapping(역방향 매핑)은 숫자형 enum에서만 자동으로 사용 가능하다고 볼 수 있습니다.

``` ts
// 숫자형 enum
enum NumericEnum {
    A = 1,
    B = 2,
    C = 3
}

console.log(NumericEnum.A);  // 출력: 1
console.log(NumericEnum[1]); // 출력: "A"

// 문자열 enum
enum StringEnum {
    A = "APPLE",
    B = "BANANA",
    C = "CHERRY"
}

console.log(StringEnum.A);     // 출력: "APPLE"
console.log(StringEnum["APPLE"]); // 출력: undefined
```

**Comment by gwangminjun** [comment]
수고하셨습니다~~
