### ISSUE TITLE
2.2.8 이터러블의 개념과 장점은 무엇인가요?

### ISSUE THREAD

**Issue by gwangminjun** [Gwangju-Web-Study/WoowahanTS_Study#7]
📝 61p

❓ 질문
이터러블의 개념과 장점은 무엇인가요?

**Comment by db-jay** [comment]
### 이터러블의 개념

1. 이터러블(inerable)은 반복 가능한 객체를 의미함.
2. JS에서 이터러블은 `[Symbol.iterator]`메서드를 구현한 객체로, 이터레이터(iterator)를 반환함.
3. 이터러블은 `next()` 메서드를 가지며, `{value, done}` 형태의 객체를 반환함.

### 이터러블의 장점

1. `for…of` 루프, `spread operator` 등을 사용하여 순회 가능.
2. 필요한 시점에 값을 생성(Lazy Evaluation)하므로 메모리를 효율적으로 사용.
3. 타입스크립트 enum을 이용한 이터러블 예시

    ```tsx
    // Color enum 정의
    enum Color {
      Red,
      Green,
      Blue
    }
    
    // EnumIterator 클래스를 만들어 이터러블로 변환
    class EnumIterator implements Iterable<string> {
	    private enumOpject: object;
	    
	    constructor(enumObject:object) {
		    this.enumObject = enumObject;
	    }
	    
	    // Symbol.etarator 메서드 구현
	    *[Symbol.iterator() {
		    for (let key in this.enumObject) {
			    if(isNaN(Number(key))) {
				    yield key;
			    }
		    }
	    }
    }
    
    // 순회 사용 예시
    const colorIterator = new EnumIterator(Color);
    
    const colorArray = [...colorIterator];
    console.log(colorArray); // ['Red', 'Green', 'Blue']
    
    ```

**Comment by hyeonseong2023** [comment]
### 이터러블의 개념
* [Symbol.iterator] 프로퍼티에 대한 구현을 가진 객체
* 반복 가능한 객체는 배열을 일반화한 객체
* 객체 {done: Boolean, value: any}을 반환하는 메서드 next()가 반드시 구현

### 이터러블의 장점
* 개발자가 직접 이터레이터를 사용하지 않고도 이터러블을 사용하여 편리하게 순회
*  Array, String, Map, Set, TypedArray, arguments 객체, DOM 컬렉션 등 여러 객체에 접근

**Comment by gwangminjun** [comment]
## 정의

iterate : (계산, 컴퓨터 처리 절차를) 반복하다
iterator : 반복자

### iterable
iterator를 리턴하는 [Symbol.iterator]() 메서드를 가진 객체
자료를 반복할 수 있는 객체

### iterator
{value : 값 , done : true/false} 형태의 iterator 객체를 리턴하는 next() 메서드를 가진 객체.
next 메서드로 순환 할 수 있는 객체


## 장점
1. 메모리 효율성
지연 평가(Lazy Evaluation)
이터러블은 데이터를 미리 모두 메모리에 로드하지 않고, 필요할 때마다 한 요소씩 계산하거나 가져오는 방식으로 동작
```ts
function* infiniteNumbers() {
  let num = 0;
  while (true) {
    yield num++;
  }
}
```
이터러블은 한 번에 하나씩 데이터를 처리하므로,<br> 
매우 큰 데이터를 다룰 때 메모리 사용을 최소화 가능 <br>
매우 큰 데이터가 있는 배열을 한 번에 처리하는 대신, <br> 
이터러블을 사용하여 한 번에 하나씩 처리하면 메모리를 크게 절약할 수 있습니다.

2. 이터레이션 문법 사용
이터러블 프로토콜을 따르는 객체라면 for...of 문과 같은 이터레이션 문법을 사용하여 <br>
자료 구조간 상호 운용성을 높일수 있습니다.
```ts
const array = [1, 2, 3];
for (const value of array) {
  console.log(value);
}
```

## 추가
java는 각 자료구조를 표준화한 아키텍처인 Java Collection Framework 의 최상위 인터페이스로 이터러블을 구현하고 있습니다
![image](https://github.com/user-attachments/assets/7766437f-010f-49ad-8dbd-8e23800651fb)



### reference
- https://inpa.tistory.com/entry/JS-%F0%9F%93%9A-%EC%9D%B4%ED%84%B0%EB%9F%AC%EB%B8%94-%EC%9D%B4%ED%84%B0%EB%A0%88%EC%9D%B4%ED%84%B0-%F0%9F%92%AF%EC%99%84%EB%B2%BD-%EC%9D%B4%ED%95%B4

**Comment by Clt689** [comment]
## 이터러블의 개념
- 이터러블(iterable)은 **반복할 수 있는**이라는 의미를 가짐.
- Symbol.iterator라는 메서드를 가지고 있어야 하며, 가장 대표적으로 배열과 문자열이 있음.
- 이터러블한 것은 for ... of 와 같은 반복문 사용 가능
   - 그 내부의 요소를 하나씩 순차적으로 접근 가능

---
## 이터러블의 장점
### 1. 메모리 효율성
이터러블을 사용하면 데이터를 미리 전부 메모리에 올리지 않고, 필요한 시점에 하나씩 가져와 처리 가능. 특히 제너레이터(generator)와 같은 이터러블은 매우 큰 데이터셋을 다룰 때 메모리를 절약할 수 있음.

### 2. 유연성
이터러블 인터페이스를 구현하는 모든 객체는 for 루프와 같은 반복문에서 동일하게 사용할 수 있다. 이는 코드를 더욱 유연하고 재사용 가능하게 만듦.

### 3. 지연 평가(lazy evaluation)
이터러블은 필요할 때만 데이터를 생성하여 계산을 지연시킬 수 있음. 이것은 성능 최적화와 관련된 중요한 특징으로, 예를 들어, 무한대의 숫자를 순회하는 이터러블도 만들 수 있음.

### 4. 단순성
이터러블을 사용하면 복잡한 데이터 처리 과정을 단순화할 수 있다. 파이썬의 내장 함수들과도 자연스럽게 통합되어 코드의 가독성을 높임.

**Comment by BaekWeb** [comment]
이터러블의 개념과 장점은 무엇인가요?

이터러블의 개념
- 반복문을 사용해서 순회할 수 있는 객체
- Array, String, Set, Map 

```
// Array
const numbers: number[] = [1, 2, 3, 4, 5];

// for...of 루프 사용
for (const number of numbers) {
  console.log(number); // 1, 2, 3, 4, 5
}

// spread 연산자 사용
const newNumbers: number[] = [...numbers];
console.log(newNumbers); // [1, 2, 3, 4, 5]
```

```
// string
const text: string = 'hello';

// for...of 루프 사용
for (const char of text) {
  console.log(char); // 'h', 'e', 'l', 'l', 'o'
}

// spread 연산자 사용
const chars: string[] = [...text];
console.log(chars); // ['h', 'e', 'l', 'l', 'o']
```

```
// set - 셋은 중복 없는 값을 저장
const uniqueNumbers: Set<number> = new Set([1, 2, 2, 3, 4]);

// for...of 루프 사용
for (const num of uniqueNumbers) {
  console.log(num); // 1, 2, 3, 4
}

// spread 연산자 사용
const numbersArray: number[] = [...uniqueNumbers];
console.log(numbersArray); // [1, 2, 3, 4]
```

```
// map - 키-값 쌍을 저장
const map: Map<string, number> = new Map([
  ['a', 1],
  ['b', 2],
  ['c', 3]
]);

// for...of 루프 사용 (키-값 쌍)
for (const [key, value] of map) {
  console.log(`${key}: ${value}`); // 'a: 1', 'b: 2', 'c: 3'
}

// spread 연산자 사용 (키-값 쌍)
const mapArray: [string, number][] = [...map];
console.log(mapArray); // [['a', 1], ['b', 2], ['c', 3]]
```

이터러블의 장점은 무엇인가요?
1. 코드의 간결화
2. 메모리 효율성
 - 지연 평가 : 한번에 로드 하지 않고 필요할 때마다 제공하는 방식
 - 메모리 소비 절감

**Comment by gwangminjun** [comment]
수고하셨습니다~~
