### ISSUE TITLE
2.2.5_"식별할 수 있는 유니온"이란 무엇인지 설명해주세요.

### ISSUE THREAD

**Issue by BaekWeb** [Gwangju-Web-Study/WoowahanTS_Study#8]
📝 p49

❓ 타입스크립트 구조적 타이핑 특징으로 추가속성을 가진 객체도 할당 할 수 있기 때문에 발생하는 문제로
    이러한 한계를 극복하고자 타입스크립트에 명목적 타이핑 언어의 특징을 가미한 식별할 수 있는 유니온 같은 방법이 생겨났다고 책에 있습니다.
    그럼 이때 식별할 수 있는 유니온이란 무엇인지 설명해주세요!

**Comment by db-jay** [comment]
### 개념 설명

식별할 수 있는 유니온(Discriminated Unions)은 TS에서 여러 타입을 하나의 유니온 타입으로 결합하면서, 각 타입을 구분할 수 있는 식별자를 가지는 패턴.

### 특징

1. 공통 식별자 : 유니온의 모든 멤버 타입이 공통으로 가지는 리터럴 타입의 속성.
2. 타입 안정성 : 컴파일러가 각 타입을 정확하게 식별할 수 있어 안정성 향상.
3. 타입 선별(narrowing) : 식별자를 사용해 특정 타입으로 범위를 좁힐 수 있음.
4. 패턴 매칭 : 조건문( switch, if ) 을 통해 각 케이스 개별처리 가능.

### 코드 예시

```tsx
interface textMsg {
  type: "text";
  content: string;
}

interface imgMsg {
  type: "image";
  url: string;
}

// Message 타입을 식별할 수 있는 유니온으로 정의
type Message = textMsg | imgMsg;

// 메시지 처리 함수 예시
function sendMessage(message: Message):void {
  switch(message.type) {
    case "text":
      console.log(message.content)
      break;
    case "image":
      console.log(message.url)
      break;
  }
}

// 사용 예시
const textMsg: Message = { type: "text", content: "Jay" };
const imageMsg: Message = { type: "image", url: "http://example.com/image.jpg" };

processMessage(textMsg);  // Jay
processMessage(imageMsg); // http://example.com/image.jpg

```

**Comment by hyeonseong2023** [comment]
### 식별할 수 있는 유니온
* 겹치지 않는 타입으로 이루어진 유니온 타입

1. 공통 식별자 속성 : 공통 속성을 사용하여 이 속성의 값에 따라 구체적인 타입 식별
1-1. 네트워크 요청, 특정 아이디를 갖는 컬럼을 쿼리, 어떤 파일명을 갖는 파일 내용을 읽어오는 경우 등에 사용
```js
interface Employee {
  type: 'Employee';
  department: string;
  salary: number;
}

interface Boss {
  type: 'Boss';
  kind: boolean;  
}

// 공통 속성인 'type'으로 식별
interface CompanyMember = Employee | Boss;
```
2. 패턴 매칭
대표적으로 switch 사용
```js
function areaWithTypo(s: Shape): number {
  switch (s.kind) {
    case "square": {
      // s의 타입 Square로 좁혀짐
      return s.size * s.size;
    }
    case "rectangl": { // 타입스크립트에서 오타로 인한 에러 지적
      // 오타 발생
      return s.height * s.width;
    }
    case "circle": {
      // s의 타입 Circle로 좁혀짐
      return Math.PI * s.radius ** 2;
    }
  }
}
// error TS2678: Type '"rectangl"' is not comparable to type '"square" | "circle" | "rectangle"'.
```

**Comment by gwangminjun** [comment]
## 리터럴 타입
정해진 값을 갖는것

## 유니온 타입 (OR 연산자(||))
값이 정해져 있지 않고 <br>
A이거나 B이다  OR 연산자(||)

### 정의방식
- 연산자 (|)를 이용 
→ 타입을 여러 개 연결하는 방식

```JS
function logText(text: string | number) {
  // ...
}
```

### 식별가능한 유니온 타입
동일한 속성의 타입을 다르게 해서 구분가능

검사 항목수에 따른 추천되는 조건문
- 적은 경우 : if 문
- 많은 경우 : switch 문


예시
```js

interface Cat {
  name: "Cat";
  sound : "야옹"
  meow(): void;
}

interface Dog {
  name: "Dog";
  sound : "멍멍"
  bark(): void;
}

//this.sound를 통해 인터페이스의 sound를 가져오고 싶었지만 
//실제 구현은 클래스나 객체에서 이루어져야 하기 때문에 클래스 선언 후 사용하였습니다

class CatImp implements Cat {
  name = "Cat";
  sound = "야옹";

  meow() {
    console.log(this.sound);
  }
}

class DogImp implements Dog {
  name = "Dog";
  sound = "멍멍";

  bark() {
    console.log(this.sound);
  }
}

function Klaxon(resource: Cat | Dog) {
  console.log(resource.sound); 

  if (resource.name === 'Cat'){
    const cat = new CatImp();
    cat.meow();
  } else {
    const dog  = new DogImp();
    dog.bark();
    }
    
}
```

## 인터섹션 타입(Intersection Type) (AND)
여러 개의 타입을 하나로 합쳐주는 역할.<br>
필요한 모든 기능을 가진 하나의 타입

### 정의방식
- 연산자(&) 이용
- 모든 속성 기입 필수

```ts
interface Person {
  name: string;
  age: number;
}
interface Developer {
  name: string;
  skill: number;
}
type Capt = Person & Developer;
{
  name: string;
  age: number;
  skill: string;
}
```



### refernce
- https://velog.io/@katej927/TypeScript-%EC%97%B0%EC%82%B0%EC%9E%90%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%ED%83%80%EC%9E%85-%EC%A0%95%EC%9D%98#-%EB%A6%AC%ED%84%B0%EB%9F%B4-%ED%83%80%EC%9E%85-literal-type

**Comment by Clt689** [comment]
타입스크립트에서 **식별할 수 있는 유니온(Discriminated Union)**
은 유니온 타입을 더 안전하고 효과적으로 사용할 수 있도록 해주는 패턴입니다. 각 타입이 공통으로 가지고 있는 "식별자" 속성을 사용하여, 해당 타입을 식별하고 처리하는 방식입니다.

## 식별할 수 있는 유니온의 구성 요소
### 1. 유니온 타입
여러 타입들을 하나로 합친 타입입니다. 예를 들어, A | B | C는 A, B, C 중 하나일 수 있는 유니온 타입입니다.

### 2. 식별자(discriminant) 속성
각 유니온 타입에 공통으로 포함된 속성으로, 해당 속성의 값에 따라 타입을 식별할 수 있습니다. 보통 이 속성은 문자열 리터럴 타입을 가지며, 각 타입마다 고유한 값을 가집니다.

### 3. 타입 가드
식별자 속성의 값에 따라 타입을 좁히는 역할을 하는 조건문입니다. 이를 통해 특정 유니온 타입을 확실하게 구분하고 그 타입에 맞는 처리를 할 수 있습니다.

---
## 예시
```ts
type Dog = {
    type: 'dog'; // 식별자 속성
    bark: () => void;
};

type Cat = {
    type: 'cat'; // 식별자 속성
    meow: () => void;
};

type Animal = Dog | Cat;

function checkAnimal(animal: Animal) {
    if (animal.type === 'dog') {
        // 여기서 animal은 Dog 타입으로 좁혀짐.
        animal.bark();
    } else if (animal.type === 'cat') {
        // 여기서 animal은 Cat 타입으로 좁혀짐.
        animal.meow();
    }
}
```

- 위 코드에서 type 속성은 "식별자"로 사용. checkAnimal 함수 안에서 animal.type을 확인하여 animal이 Dog인지 Cat인지 식별하고, 타입에 따라 적절한 메서드를 호출할 수 있다.

**Comment by BaekWeb** [comment]
타입스크립테에서 유니온 타입을 사용할 때 , 각 타입이 동일한 속성을 가지고 있으면
타입스크립트는 속성만으로 타입을 구분 할 수 없다.
이것을 구분할 수 있게 해주는 것이 식별할 수 있는 유니온 입니다.

ex)
기본 유니온 타입: 여러 타입을 하나로 묶는 방법

```tsx
type Cat = {
  meow: () => void;
};

type Dog = {
  bark: () => void;
};

type Animal = Cat | Dog;
```

식별할 수 있는 유니온: 각 타입을 구분할 수 있는 공통 속성을 추가하여 문제를 해결

```tsx
type Cat = {
  type: 'cat';
  meow: () => void;
};

type Dog = {
  type: 'dog';
  bark: () => void;
};

type Animal = Cat | Dog;

```

구분 방법 사용하기: 이 식별자 속성을 사용해서 코드에서 타입을 분기 처리

```tsx
function makeSound(animal: Animal) {
  if (animal.type === 'cat') {
    animal.meow(); // Cat에만 있는 메서드
  } else {
    animal.bark(); // Dog에만 있는 메서드
  }
}

```

**Comment by hyeonseong2023** [comment]
https://github.com/Gwangju-Web-Study/WoowahanTS_Study/issues/8#issuecomment-2295020580
```js
interface Person {
  name: string;
  age: number;
}
interface Developer {
  name: number;
  skill: number;
}
type Capt = Person & Developer;
```
만약 공통 name의 타입이 서로 다른 채 합친다면 해당 인덱스는 never 타입으로 아무 것도 넣을 수 없게 된다.
