### ISSUE TITLE
2.2.8_어떤 상황에서 어떤 키워드의 타입을 사용해야 좋을까요?

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#9]
📝 60p

❓ 질문
타입스크립트에서 자바스크립트의 키워드가 타입으로 해석되는 키워드에는 type, interface, class, enum 이렇게 4가지가 있습니다.
어떤 상황에서 어떤 키워드를 사용하면 좋을지 비교하여 설명해주세요!
(이론에 기반하여 설명해주셔도 좋고, 사용한다고 가정했을 때 상황으로 설명하셔도 좋습니다😎)

**Comment by db-jay** [comment]
### 개념 기반 비교

1. type
    1. 단순하게 기존 타입을 조합하거나 정의하는 데 유용함.
    2. 타입 별칭을 만들거나 `union` `intersection` 등 복잡한 타입을 정의할 때 사용.
    3. 한 번 정의되면 재정의 불가.
2. interface
    1. 확장(extends)이 가능하여 코드 재사용성이 높음.
    2. 객체 지향 프로그래밍의 `interface` 개념과 유사함.
    3. 선언 병합(Declaration Merging)이 가능해 동일한 이름으로 재선언 가능.
3. class
    1. 인스턴스 생성, 상속, 캡슐화 등 OOP 개념 구현 가능.
    2. 런타임에 실제 값으로 존재함.
    3. 타입으로도 사용 가능함.
4. enum
    1. 숫자 or 문자열 값을 관련된 가진 상수들의 집합을 정의할 때 사용함.
    2. 컴파일시 객체로 변환되어 런타임에 존재함.

### 코드 비교

```tsx
// 1. type
type Point = {
	x: numner;
	y: number;
}
type ID = string | number;

// 2. interface
interface Shape {
	getArea(): number;
}

interface Circle extends Shape {
	radius: number;
}

interface Circle { // interface Circle 재선언(Declaration Merging)
	color: string;
}

// 3. class
class Rectangle implements Shape {
	constructor(private width:number, private height: number) {}
	
	getArea(): number {
		return this.width * this.height
	}
}

// 4. enum
enum Direction {
  Up,
  Down,
  Left,
  Right
}

// 타입별 사용 예시 :)
const point:Point = {x:101, y:20}; // 1. type
const id: ID = "JayTest" // 1.type

const circle:Circle = { // 2. interface
	ratius: 5,
	color: "green",
	getArea: () => Math.PI * 5 * 5
}

const recetangle = new Rectangle(4,5) // 3. class
console.log(rectangle.getArea()); // = 20

const direction = Direction.Up; // 4. enum
console.log(Direction[direction]) // "Up" (역방향 매핑)
```

**Comment by gwangminjun** [comment]
## 개념
1. type
    - 타입의 새로운 이름을 만드는것
    - 상속이 불가능 하기때문에 유연한 코드 작성을 위해서 인터페이스 사용을 권장
2. interface
    - 객체의 구조를 정의하기 위해 사용되는 예약어
    - 인터페이스에 선언된 프로퍼티 또는 메서들의 구현을 가제해 일관성을 유지
    - 객체의 구조를 정의하지만, 메서드 구현을 직접 포함하지는 않습니다. 
3. class
    - 속성과 메서드에 대한 타입을 명시할 수 있다.
    - 객체 지향 개념을 구현하기 위해 사용
    - 상속 가능
4. enum
    - 열거형
    - 특정 값들의 집합
    - 상수값을 대신하여 사용함


## 사용
```ts
//1. type
type Person = {
  id: number;
  name: string;
  email: string;
}

//2. interface
//상속
interface Person {
    name: string;
    age: number;
}

interface Developer extends Person {
    language: string;
}

const person: Developer = {
    language: "TypeScript",
    age: 28,
    name: "minjun",
}

//3. class 
//상속
class Animal {
    move(distanceInMeters: number): void {
        console.log(`${distanceInMeters}m 이동했습니다.`);
    }
}

class Dog extends Animal {
    speak(): void {
        console.log("멍멍");
    }
}

class Cat extends Animal {
    speak(): void {
        console.log("야옹");
    }
}

const dog = new Dog();
dog.move(10); // 10m 이동했습니다.
dog.speak(); // 멍멍

const cat = new Cat();
Cat.move(15); // 15m 이동했습니다.
Cat.speak(); // 야옹

//4. enum
enum Computer {
  Monitor = 3,
  Mouse = 7,
  Keyboard = 1,
  Speaker = 5,
}

let a: Computer = Computer.Keyboard;
let b: number = Computer.Mouse;

console.log(a); // 1
console.log(b); // 7
```

### reference
- https://velog.io/@coding0206/TypeScript-Enum-Interface-TypeClass
- https://summerr.tistory.com/83

**Comment by BaekWeb** [comment]
type
- 복잡한 타입을 정의 하거나 조합할 때 사용.
- 타입 별칭을 만들어 여러 타입을 조합하거나 특정 형식을 단순화
[적합한 경우]
조건에 따라 타입을 결정해야 할 때

interface
- 객체의 구조를 정의할 때 사용
- 여러 인터페이스를 조합하거나 확장
[적합한 경우]
객체와 클래스의 구조를 명확히 정의하고 인터페이스를 상속하여 확장할때 

class
-클래스의 구조를 정의할 때 사용
- 생성자, 메서드, 속성을 정의해 객체를 생성
[적합한 경우]
객체 지향 프로그래밍의 기본 개념인 클래스와 인스턴스를 사용할 때.
속성, 메서드, 접근 제어자, 상속 등을 정의하여 객체의 상태와 동작을 구현할 때.

enum
- 상수 집합을 정의할 때 사용

**Comment by Clt689** [comment]
##  1. type
type 키워드는 타입 별칭(type alias)을 정의하는 데 사용됩니다. 즉, 특정 타입에 이름을 붙여주는 역할을 합니다.
### 사용 시기
- 유니온 또는 교차 타입
: 복잡한 유니온(합집합)이나 교차(교집합) 타입을 정의할 때
- 프리미티브 타입
: 문자열, 숫자, 배열, 객체 리터럴 타입 등 다양한 타입을 정의할 때
- 함수 시그니처 : 함수 타입을 정의할 때

<br>

## 2. interface
interface 키워드는 객체 타입을 정의하고, 특정 구조를 가진 객체를 지정하는 데 사용됩니다.
### 사용 시기
- 객체 타입 정의: 주로 객체의 구조를 정의할 때
- 클래스와의 호환성: 클래스가 특정 구조를 따르도록 강제할 때
- 확장성: 다른 인터페이스를 상속받거나, 같은 이름으로 선언 병합(declaration merging)을 통해 확장할 때

<br>

## 3. class
class 키워드는 객체의 인스턴스를 생성할 수 있는 템플릿을 정의합니다. 클래스는 객체의 상태(필드)와 동작(메서드)을 정의하며, 객체 지향 프로그래밍의 기본 단위입니다.

### 사용 시기
- 객체 지향 프로그래밍(OOP): 객체 지향 설계를 할 때
- 상속과 다형성: 클래스를 확장하고, 상속 관계를 구현할 때
- 인스턴스 생성: 특정 구조를 가진 객체를 생성할 때

<br>

## 4. enum
enum 키워드는 열거형을 정의하며, 여러 상수들을 하나의 그룹으로 묶어 의미 있는 이름을 부여할 수 있게 해줍니다.

### 사용 시기
- 상수 집합: 관련된 상수들을 그룹화할 때
- 정의된 범주의 값 사용: 명확하게 제한된 값들 중 하나를 사용할 때

**Comment by hyeonseong2023** [comment]
### 1. type
* 타입 별칭을 생성할 때 사용
```js
// 복잡한 타입을 조합할 경우
type Point = {
  x: number;
  y: number;
};

type ColoredPoint = Point & {
  color: string;
};
```

### 2. interface
용도: 객체의 구조를 정의할 때 사용
```js
// 여러 사용자로 구분하여 확장하는 경우
interface User {
  id: number;
  name: string;
}

interface Admin extends User {
  adminLevel: number;
}
```

### 3. class
용도: 객체의 인스턴스 타입을 정의
```js
class Person {
  constructor(public name: string, public age: number) {}

  greet() {
    console.log(`Hello, my name is ${this.name}`);
  }
}

const person: Person = new Person('Alice', 30);
```

### 4. enum
용도: 명명된 상수 집합의 값을 타입으로 사용
```js
enum Color {
  Red = 'RED',
  Green = 'GREEN',
  Blue = 'BLUE'
}

const color: Color = Color.Green;
```
